AC_CONFIG_FILES([nova/Makefile
        nova/knowledge/Makefile
        nova/sqlite3/Makefile
        nova/disphelper/Makefile
        nova/libcfnova/Makefile
        nova/libcfagent/Makefile
        nova/libcfmonitord/Makefile
        nova/libcfreport/Makefile
        nova/libcfserverd/Makefile
        nova/cf-know/Makefile
        nova/cf-hub/Makefile
        nova/api/Makefile
        nova/cfmod/Makefile
        nova/tests/unit/Makefile])
