
/*
Copyright (c) 2011 Sencha Inc. - Author: Nicolas Garcia Belmonte (http://philogb.github.com/)

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

 */
 
 (function(){window.$jit=function(a){var a=a||window,c;for(c in $jit)$jit[c].$extend&&(a[c]=$jit[c])};$jit.version="2.0.1";var h=function(a){return document.getElementById(a)};h.empty=function(){};h.extend=function(a,c){for(var b in c||{})a[b]=c[b];return a};h.lambda=function(a){return typeof a=="function"?a:function(){return a}};h.time=Date.now||function(){return+new Date};h.splat=function(a){var c=h.type(a);return c?c!="array"?[a]:a:[]};h.type=function(a){var c=h.type.s.call(a).match(/^\[object\s(.*)\]$/)[1].toLowerCase();
if(c!="object")return c;if(a&&a.$$family)return a.$$family;return a&&a.nodeName&&a.nodeType==1?"element":c};h.type.s=Object.prototype.toString;h.each=function(a,c){if(h.type(a)=="object")for(var b in a)c(a[b],b);else{b=0;for(var d=a.length;b<d;b++)c(a[b],b)}};h.indexOf=function(a,c){if(Array.indexOf)return a.indexOf(c);for(var b=0,d=a.length;b<d;b++)if(a[b]===c)return b;return-1};h.map=function(a,c){var b=[];h.each(a,function(a,e){b.push(c(a,e))});return b};h.reduce=function(a,c,b){var d=a.length;
if(d==0)return b;for(var e=arguments.length==3?b:a[--d];d--;)e=c(e,a[d]);return e};h.merge=function(){for(var a={},c=0,b=arguments.length;c<b;c++){var d=arguments[c];if(h.type(d)=="object")for(var e in d){var f=d[e],g=a[e];a[e]=g&&h.type(f)=="object"&&h.type(g)=="object"?h.merge(g,f):h.unlink(f)}}return a};h.unlink=function(a){var c;switch(h.type(a)){case "object":c={};for(var b in a)c[b]=h.unlink(a[b]);break;case "array":c=[];b=0;for(var d=a.length;b<d;b++)c[b]=h.unlink(a[b]);break;default:return a}return c};
h.zip=function(){if(arguments.length===0)return[];for(var a=0,c=[],b=arguments.length,d=arguments[0].length;a<d;a++){for(var e=0,f=[];e<b;e++)f.push(arguments[e][a]);c.push(f)}return c};h.rgbToHex=function(a,c){if(a.length<3)return null;if(a.length==4&&a[3]==0&&!c)return"transparent";for(var b=[],d=0;d<3;d++){var e=(a[d]-0).toString(16);b.push(e.length==1?"0"+e:e)}return c?b:"#"+b.join("")};h.hexToRgb=function(a){if(a.length!=7){a=a.match(/^#?(\w{1,2})(\w{1,2})(\w{1,2})$/);a.shift();if(a.length!=
3)return null;for(var c=[],b=0;b<3;b++){var d=a[b];d.length==1&&(d+=d);c.push(parseInt(d,16))}return c}else return a=parseInt(a.slice(1),16),[a>>16,a>>8&255,a&255]};h.destroy=function(a){h.clean(a);a.parentNode&&a.parentNode.removeChild(a);a.clearAttributes&&a.clearAttributes()};h.clean=function(a){for(var a=a.childNodes,c=0,b=a.length;c<b;c++)h.destroy(a[c])};h.addEvent=function(a,c,b){a.addEventListener?a.addEventListener(c,b,!1):a.attachEvent("on"+c,b)};h.addEvents=function(a,c){for(var b in c)h.addEvent(a,
b,c[b])};h.hasClass=function(a,c){return(" "+a.className+" ").indexOf(" "+c+" ")>-1};h.addClass=function(a,c){if(!h.hasClass(a,c))a.className=a.className+" "+c};h.removeClass=function(a,c){a.className=a.className.replace(RegExp("(^|\\s)"+c+"(?:\\s|$)"),"$1")};h.getPos=function(a){var c=function(a){for(var d={x:0,y:0};a&&!/^(?:body|html)$/i.test(a.tagName);)d.x+=a.offsetLeft,d.y+=a.offsetTop,a=a.offsetParent;return d}(a),a=function(a){for(var d={x:0,y:0};a&&!/^(?:body|html)$/i.test(a.tagName);)d.x+=
a.scrollLeft,d.y+=a.scrollTop,a=a.parentNode;return d}(a);return{x:c.x-a.x,y:c.y-a.y}};h.event={get:function(a,c){return a||(c||window).event},getWheel:function(a){return a.wheelDelta?a.wheelDelta/120:-(a.detail||0)/3},isRightClick:function(a){return a.which==3||a.button==2},getPos:function(a,c){var c=c||window,a=a||c.event,b=c.document,b=b.documentElement||b.body;a.touches&&a.touches.length&&(a=a.touches[0]);return{x:a.pageX||a.clientX+b.scrollLeft,y:a.pageY||a.clientY+b.scrollTop}},stop:function(a){a.stopPropagation&&
a.stopPropagation();a.cancelBubble=!0;a.preventDefault?a.preventDefault():a.returnValue=!1}};$jit.util=$jit.id=h;var l=function(a){var a=a||{},c=function(){for(var a in this)typeof this[a]!="function"&&(this[a]=h.unlink(this[a]));this.constructor=c;if(l.prototyping)return this;a=this.initialize?this.initialize.apply(this,arguments):this;this.$$family="class";return a},b;for(b in l.Mutators)a[b]&&(a=l.Mutators[b](a,a[b]),delete a[b]);h.extend(c,this);c.constructor=l;c.prototype=a;return c};l.Mutators=
{Implements:function(a,c){h.each(h.splat(c),function(c){l.prototyping=c;var c=typeof c=="function"?new c:c,d;for(d in c)d in a||(a[d]=c[d]);delete l.prototyping});return a}};h.extend(l,{inherit:function(a,c){for(var b in c){var d=c[b],e=a[b],f=h.type(d);e&&f=="function"?d!=e&&l.override(a,b,d):a[b]=f=="object"?h.merge(e,d):d}return a},override:function(a,c,b){var d=l.prototyping;d&&a[c]!=d[c]&&(d=null);a[c]=function(){var e=this.parent;this.parent=d?d[c]:a[c];var f=b.apply(this,arguments);this.parent=
e;return f}}});l.prototype.implement=function(){var a=this.prototype;h.each(Array.prototype.slice.call(arguments||[]),function(c){l.inherit(a,c)});return this};$jit.Class=l;$jit.json={prune:function(a,c){this.each(a,function(a,d){if(d==c&&a.children)delete a.children,a.children=[]})},getParent:function(a,c){if(a.id==c)return!1;var b=a.children;if(b&&b.length>0)for(var d=0;d<b.length;d++)if(b[d].id==c)return a;else{var e=this.getParent(b[d],c);if(e)return e}return!1},getSubtree:function(a,c){if(a.id==
c)return a;for(var b=0,d=a.children;d&&b<d.length;b++){var e=this.getSubtree(d[b],c);if(e!=null)return e}return null},eachLevel:function(a,c,b,d){if(c<=b&&(d(a,c),a.children))for(var e=0,a=a.children;e<a.length;e++)this.eachLevel(a[e],c+1,b,d)},each:function(a,c){this.eachLevel(a,0,Number.MAX_VALUE,c)}};$jit.Trans={$extend:!0,linear:function(a){return a}};var C=$jit.Trans;(function(){var a=function(a,b){b=h.splat(b);return h.extend(a,{easeIn:function(d){return a(d,b)},easeOut:function(d){return 1-
a(1-d,b)},easeInOut:function(d){return d<=0.5?a(2*d,b)/2:(2-a(2*(1-d),b))/2}})};h.each({Pow:function(a,b){return Math.pow(a,b[0]||6)},Expo:function(a){return Math.pow(2,8*(a-1))},Circ:function(a){return 1-Math.sin(Math.acos(a))},Sine:function(a){return 1-Math.sin((1-a)*Math.PI/2)},Back:function(a,b){b=b[0]||1.618;return Math.pow(a,2)*((b+1)*a-b)},Bounce:function(a){for(var b,d=0,e=1;;d+=e,e/=2)if(a>=(7-4*d)/11){b=e*e-Math.pow((11-6*d-11*a)/4,2);break}return b},Elastic:function(a,b){return Math.pow(2,
10*--a)*Math.cos(20*a*Math.PI*(b[0]||1)/3)}},function(c,b){C[b]=a(c)});h.each(["Quad","Cubic","Quart","Quint"],function(c,b){C[c]=a(function(a){return Math.pow(a,[b+2])})})})();var J=new l({initialize:function(a){this.setOptions(a)},setOptions:function(a){this.opt=h.merge({duration:2500,fps:40,transition:C.Quart.easeInOut,compute:h.empty,complete:h.empty,link:"ignore"},a||{});return this},step:function(){var a=h.time(),c=this.opt;a<this.time+c.duration?(a=c.transition((a-this.time)/c.duration),c.compute(a)):
(this.timer=clearInterval(this.timer),c.compute(1),c.complete())},start:function(){if(!this.check())return this;this.time=0;this.startTimer();return this},startTimer:function(){var a=this,c=this.opt.fps;if(this.timer)return!1;this.time=h.time()-this.time;this.timer=setInterval(function(){a.step()},Math.round(1E3/c));return!0},pause:function(){this.stopTimer();return this},resume:function(){this.startTimer();return this},stopTimer:function(){if(!this.timer)return!1;this.time=h.time()-this.time;this.timer=
clearInterval(this.timer);return!0},check:function(){if(!this.timer)return!0;if(this.opt.link=="cancel")return this.stopTimer(),!0;return!1}}),v=function(){for(var a=arguments,c=0,b=a.length,d={};c<b;c++){var e=v[a[c]];e.$extend?h.extend(d,e):d[a[c]]=e}return d};v.BarChart={$extend:!0,animate:!0,type:"stacked",labelOffset:3,barsOffset:0,hoveredColor:"#9fd4ff",orientation:"horizontal",showAggregates:!0,showLabels:!0,Tips:{enable:!1,onShow:h.empty,onHide:h.empty},Events:{enable:!1,onClick:h.empty}};
v.Margin={$extend:!1,top:0,left:0,right:0,bottom:0};v.Canvas={$extend:!0,injectInto:"id",type:"2D",width:!1,height:!1,useCanvas:!1,withLabels:!0,background:!1,Scene:{Lighting:{enable:!1,ambient:[1,1,1],directional:{direction:{x:-100,y:-100,z:-100},color:[0.5,0.3,0.1]}}}};v.Tree={$extend:!0,orientation:"left",subtreeOffset:8,siblingOffset:5,indent:10,multitree:!1,align:"center"};v.Node={$extend:!1,overridable:!1,type:"circle",color:"#ccb",alpha:1,dim:3,height:20,width:90,autoHeight:!1,autoWidth:!1,
lineWidth:1,transform:!0,align:"center",angularWidth:1,span:1,CanvasStyles:{}};v.Edge={$extend:!1,overridable:!1,type:"line",color:"#ccb",lineWidth:1,dim:15,alpha:1,epsilon:7,CanvasStyles:{}};v.Fx={$extend:!0,fps:40,duration:2500,transition:$jit.Trans.Quart.easeInOut,clearCanvas:!0};v.Label={$extend:!1,overridable:!1,type:"HTML",style:" ",size:10,family:"sans-serif",textAlign:"center",textBaseline:"alphabetic",color:"#fff"};v.Tips={$extend:!1,enable:!1,type:"auto",offsetX:20,offsetY:20,force:!1,onShow:h.empty,
onHide:h.empty};v.NodeStyles={$extend:!1,enable:!1,type:"auto",stylesHover:!1,stylesClick:!1};v.Events={$extend:!1,enable:!1,enableForEdges:!1,type:"auto",onClick:h.empty,onRightClick:h.empty,onMouseMove:h.empty,onMouseEnter:h.empty,onMouseLeave:h.empty,onDragStart:h.empty,onDragMove:h.empty,onDragCancel:h.empty,onDragEnd:h.empty,onTouchStart:h.empty,onTouchMove:h.empty,onTouchEnd:h.empty,onMouseWheel:h.empty};v.Navigation={$extend:!1,enable:!1,type:"auto",panning:!1,zooming:!1};v.Controller={$extend:!0,
onBeforeCompute:h.empty,onAfterCompute:h.empty,onCreateLabel:h.empty,onPlaceLabel:h.empty,onComplete:h.empty,onBeforePlotLine:h.empty,onAfterPlotLine:h.empty,onBeforePlotNode:h.empty,onAfterPlotNode:h.empty,request:!1};var D={initialize:function(a,c){this.viz=c;this.canvas=c.canvas;this.config=c.config[a];this.nodeTypes=c.fx.nodeTypes;var b=this.config.type;this.labelContainer=(this.dom=b=="auto"?c.config.Label.type!="Native":b!="Native")&&c.labels.getLabelContainer();this.isEnabled()&&this.initializePost()},
initializePost:h.empty,setAsProperty:h.lambda(!1),isEnabled:function(){return this.config.enable},isLabel:function(a,c,b){var a=h.event.get(a,c),c=this.labelContainer,d=a.target||a.srcElement,a=a.relatedTarget;return b?a&&a==this.viz.canvas.getCtx().canvas&&!!d&&this.isDescendantOf(d,c):this.isDescendantOf(d,c)},isDescendantOf:function(a,c){for(;a&&a.parentNode;){if(a.parentNode==c)return a;a=a.parentNode}return!1}},F={onMouseUp:h.empty,onMouseDown:h.empty,onMouseMove:h.empty,onMouseOver:h.empty,
onMouseOut:h.empty,onMouseWheel:h.empty,onTouchStart:h.empty,onTouchMove:h.empty,onTouchEnd:h.empty,onTouchCancel:h.empty},P=new l({initialize:function(a){this.viz=a;this.canvas=a.canvas;this.edge=this.node=!1;this.registeredObjects=[];this.attachEvents()},attachEvents:function(){var a=this.canvas.getElement(),c=this;a.oncontextmenu=h.lambda(!1);h.addEvents(a,{mouseup:function(a,b){var f=h.event.get(a,b);c.handleEvent("MouseUp",a,b,c.makeEventObject(a,b),h.event.isRightClick(f))},mousedown:function(a,
b){var f=h.event.get(a,b);c.handleEvent("MouseDown",a,b,c.makeEventObject(a,b),h.event.isRightClick(f))},mousemove:function(a,b){c.handleEvent("MouseMove",a,b,c.makeEventObject(a,b))},mouseover:function(a,b){c.handleEvent("MouseOver",a,b,c.makeEventObject(a,b))},mouseout:function(a,b){c.handleEvent("MouseOut",a,b,c.makeEventObject(a,b))},touchstart:function(a,b){c.handleEvent("TouchStart",a,b,c.makeEventObject(a,b))},touchmove:function(a,b){c.handleEvent("TouchMove",a,b,c.makeEventObject(a,b))},touchend:function(a,
b){c.handleEvent("TouchEnd",a,b,c.makeEventObject(a,b))}});var b=function(a,b){var f=h.event.get(a,b),f=h.event.getWheel(f);c.handleEvent("MouseWheel",a,b,f)};!document.getBoxObjectFor&&window.mozInnerScreenX==null?h.addEvent(a,"mousewheel",b):a.addEventListener("DOMMouseScroll",b,!1)},register:function(a){this.registeredObjects.push(a)},handleEvent:function(){for(var a=Array.prototype.slice.call(arguments),c=a.shift(),b=0,d=this.registeredObjects,e=d.length;b<e;b++)d[b]["on"+c].apply(d[b],a)},makeEventObject:function(a,
c){var b=this,d=this.viz.graph,e=this.viz.fx,f=e.nodeTypes,g=e.edgeTypes;return{pos:!1,node:!1,edge:!1,contains:!1,getNodeCalled:!1,getEdgeCalled:!1,getPos:function(){var d=b.viz.canvas,e=d.getSize(),f=d.getPos(),g=d.translateOffsetX,n=d.translateOffsetY,p=d.scaleOffsetX,d=d.scaleOffsetY,z=h.event.getPos(a,c);return this.pos={x:(z.x-f.x-e.width/2-g)*1/p,y:(z.y-f.y-e.height/2-n)*1/d}},getNode:function(){if(this.getNodeCalled)return this.node;this.getNodeCalled=!0;for(var a in d.nodes){var c=d.nodes[a],
g=c&&f[c.getData("type")];if(g=g&&g.contains&&g.contains.call(e,c,this.getPos()))return this.contains=g,b.node=this.node=c}return b.node=this.node=!1},getEdge:function(){if(this.getEdgeCalled)return this.edge;this.getEdgeCalled=!0;var a={},c;for(c in d.edges){var f=d.edges[c];a[c]=!0;for(var h in f)if(!(h in a)){var n=f[h],p=n&&g[n.getData("type")];if(p=p&&p.contains&&p.contains.call(e,n,this.getPos()))return this.contains=p,b.edge=this.edge=n}}return b.edge=this.edge=!1},getContains:function(){if(this.getNodeCalled)return this.contains;
this.getNode();return this.contains}}}}),y={initializeExtras:function(){var a=new P(this),c=this;h.each(["NodeStyles","Tips","Navigation","Events"],function(b){var d=new y.Classes[b](b,c);d.isEnabled()&&a.register(d);d.setAsProperty()&&(c[b.toLowerCase()]=d)})},Classes:{}};y.Classes.Events=new l({Implements:[D,F],initializePost:function(){this.fx=this.viz.fx;this.ntypes=this.viz.fx.nodeTypes;this.etypes=this.viz.fx.edgeTypes;this.moved=this.touchMoved=this.touched=this.pressed=this.hovered=!1},setAsProperty:h.lambda(!0),
onMouseUp:function(a,c,b,d){a=h.event.get(a,c);if(!this.moved)if(d)this.config.onRightClick(this.hovered,b,a);else this.config.onClick(this.pressed,b,a);if(this.pressed){if(this.moved)this.config.onDragEnd(this.pressed,b,a);else this.config.onDragCancel(this.pressed,b,a);this.pressed=this.moved=!1}},onMouseOut:function(a,c,b){var d=h.event.get(a,c),e;if(this.dom&&(e=this.isLabel(a,c,!0)))this.config.onMouseLeave(this.viz.graph.getNode(e.id),b,d),this.hovered=!1;else{a=d.relatedTarget;for(c=this.canvas.getElement();a&&
a.parentNode;){if(c==a.parentNode)return;a=a.parentNode}if(this.hovered)this.config.onMouseLeave(this.hovered,b,d),this.hovered=!1}},onMouseOver:function(a,c,b){var d=h.event.get(a,c),e;if(this.dom&&(e=this.isLabel(a,c,!0)))this.hovered=this.viz.graph.getNode(e.id),this.config.onMouseEnter(this.hovered,b,d)},onMouseMove:function(a,c,b){a=h.event.get(a,c);if(this.pressed)this.moved=!0,this.config.onDragMove(this.pressed,b,a);else if(this.dom)this.config.onMouseMove(this.hovered,b,a);else{if(this.hovered){var c=
this.hovered,d=c.nodeFrom?this.etypes[c.getData("type")]:this.ntypes[c.getData("type")];if(d&&d.contains&&d.contains.call(this.fx,c,b.getPos())){this.config.onMouseMove(c,b,a);return}else this.config.onMouseLeave(c,b,a),this.hovered=!1}if(this.hovered=b.getNode()||this.config.enableForEdges&&b.getEdge())this.config.onMouseEnter(this.hovered,b,a);else this.config.onMouseMove(!1,b,a)}},onMouseWheel:function(a,c,b){this.config.onMouseWheel(b,h.event.get(a,c))},onMouseDown:function(a,c,b){var d=h.event.get(a,
c);if(this.dom){if(a=this.isLabel(a,c))this.pressed=this.viz.graph.getNode(a.id)}else this.pressed=b.getNode()||this.config.enableForEdges&&b.getEdge();this.pressed&&this.config.onDragStart(this.pressed,b,d)},onTouchStart:function(a,c,b){var d=h.event.get(a,c),e;(this.touched=this.dom&&(e=this.isLabel(a,c))?this.viz.graph.getNode(e.id):b.getNode()||this.config.enableForEdges&&b.getEdge())&&this.config.onTouchStart(this.touched,b,d)},onTouchMove:function(a,c,b){a=h.event.get(a,c);if(this.touched)this.touchMoved=
!0,this.config.onTouchMove(this.touched,b,a)},onTouchEnd:function(a,c,b){a=h.event.get(a,c);if(this.touched){if(this.touchMoved)this.config.onTouchEnd(this.touched,b,a);else this.config.onTouchCancel(this.touched,b,a);this.touched=this.touchMoved=!1}}});y.Classes.Tips=new l({Implements:[D,F],initializePost:function(){if(document.body){var a=h("_tooltip")||document.createElement("div");a.id="_tooltip";a.className="tip";h.extend(a.style,{position:"absolute",display:"none",zIndex:13E3});document.body.appendChild(a);
this.tip=a;this.node=!1}},setAsProperty:h.lambda(!0),onMouseOut:function(a,c){h.event.get(a,c);if(this.dom&&this.isLabel(a,c,!0))this.hide(!0);else{for(var b=a.relatedTarget,d=this.canvas.getElement();b&&b.parentNode;){if(d==b.parentNode)return;b=b.parentNode}this.hide(!1)}},onMouseOver:function(a,c){var b;if(this.dom&&(b=this.isLabel(a,c,!1)))this.node=this.viz.graph.getNode(b.id),this.config.onShow(this.tip,this.node,b)},onMouseMove:function(a,c,b){this.dom&&this.isLabel(a,c)&&this.setTooltipPosition(h.event.getPos(a,
c));if(!this.dom){var d=b.getNode();if(d){if(this.config.force||!this.node||this.node.id!=d.id)this.node=d,this.config.onShow(this.tip,d,b.getContains());this.setTooltipPosition(h.event.getPos(a,c))}else this.hide(!0)}},setTooltipPosition:function(a){var c=this.tip,b=c.style,d=this.config;b.display="";var e={height:document.body.clientHeight,width:document.body.clientWidth},c={width:c.offsetWidth,height:c.offsetHeight},f=d.offsetX,d=d.offsetY;b.top=(a.y+d+c.height>e.height?a.y-c.height-d:a.y+d)+"px";
b.left=(a.x+c.width+f>e.width?a.x-c.width-f:a.x+f)+"px"},hide:function(a){this.tip.style.display="none";a&&this.config.onHide()}});y.Classes.NodeStyles=new l({Implements:[D,F],initializePost:function(){this.fx=this.viz.fx;this.types=this.viz.fx.nodeTypes;this.nStyles=this.config;this.nodeStylesOnHover=this.nStyles.stylesHover;this.nodeStylesOnClick=this.nStyles.stylesClick;this.hoveredNode=!1;this.fx.nodeFxAnimation=new J;this.move=this.down=!1},onMouseOut:function(a,c){this.down=this.move=!1;if(this.hoveredNode){this.dom&&
this.isLabel(a,c,!0)&&this.toggleStylesOnHover(this.hoveredNode,!1);for(var b=a.relatedTarget,d=this.canvas.getElement();b&&b.parentNode;){if(d==b.parentNode)return;b=b.parentNode}this.toggleStylesOnHover(this.hoveredNode,!1);this.hoveredNode=!1}},onMouseOver:function(a,c){var b;if(this.dom&&(b=this.isLabel(a,c,!0)))if(b=this.viz.graph.getNode(b.id),!b.selected)this.hoveredNode=b,this.toggleStylesOnHover(this.hoveredNode,!0)},onMouseDown:function(a,c,b,d){if(!d){var e;if(this.dom&&(e=this.isLabel(a,
c)))this.down=this.viz.graph.getNode(e.id);else if(!this.dom)this.down=b.getNode();this.move=!1}},onMouseUp:function(a,c,b,d){if(!d){if(!this.move)this.onClick(b.getNode());this.down=this.move=!1}},getRestoredStyles:function(a,c){var b={},d=this["nodeStylesOn"+c],e;for(e in d)b[e]=a.styles["$"+e];return b},toggleStylesOnHover:function(a,c){this.nodeStylesOnHover&&this.toggleStylesOn("Hover",a,c)},toggleStylesOnClick:function(a,c){this.nodeStylesOnClick&&this.toggleStylesOn("Click",a,c)},toggleStylesOn:function(a,
c,b){var d=this.viz;if(b){if(!c.styles)c.styles=h.merge(c.data,{});for(var e in this["nodeStylesOn"+a])b="$"+e,b in c.styles||(c.styles[b]=c.getData(e));d.fx.nodeFx(h.extend({elements:{id:c.id,properties:this["nodeStylesOn"+a]},transition:C.Quart.easeOut,duration:300,fps:40},this.config))}else a=this.getRestoredStyles(c,a),d.fx.nodeFx(h.extend({elements:{id:c.id,properties:a},transition:C.Quart.easeOut,duration:300,fps:40},this.config))},onClick:function(a){if(a){var c=this.nodeStylesOnClick;if(c)a.selected?
(this.toggleStylesOnClick(a,!1),delete a.selected):(this.viz.graph.eachNode(function(a){if(a.selected){for(var d in c)a.setData(d,a.styles["$"+d],"end");delete a.selected}}),this.toggleStylesOnClick(a,!0),a.selected=!0,delete a.hovered,this.hoveredNode=!1)}},onMouseMove:function(a,c,b){if(this.down)this.move=!0;if(!this.dom||!this.isLabel(a,c)){var d=this.nodeStylesOnHover;if(d&&!this.dom){if(this.hoveredNode&&(a=this.types[this.hoveredNode.getData("type")])&&a.contains&&a.contains.call(this.fx,this.hoveredNode,
b.getPos()))return;b=b.getNode();if((this.hoveredNode||b)&&!b.hovered)if(b&&!b.selected)this.fx.nodeFxAnimation.stopTimer(),this.viz.graph.eachNode(function(a){if(a.hovered&&!a.selected){for(var b in d)a.setData(b,a.styles["$"+b],"end");delete a.hovered}}),b.hovered=!0,this.hoveredNode=b,this.toggleStylesOnHover(b,!0);else if(this.hoveredNode&&!this.hoveredNode.selected)this.fx.nodeFxAnimation.stopTimer(),this.toggleStylesOnHover(this.hoveredNode,!1),delete this.hoveredNode.hovered,this.hoveredNode=
!1}}}});y.Classes.Navigation=new l({Implements:[D,F],initializePost:function(){this.pressed=this.pos=!1},onMouseWheel:function(a,c,b){this.config.zooming&&(h.event.stop(h.event.get(a,c)),a=1+b*(this.config.zooming/1E3),this.canvas.scale(a,a))},onMouseDown:function(a,c,b){if(this.config.panning&&!(this.config.panning=="avoid nodes"&&(this.dom?this.isLabel(a,c):b.getNode()))){this.pressed=!0;this.pos=b.getPos();var a=this.canvas,c=a.translateOffsetX,b=a.translateOffsetY,d=a.scaleOffsetY;this.pos.x*=
a.scaleOffsetX;this.pos.x+=c;this.pos.y*=d;this.pos.y+=b}},onMouseMove:function(a,c,b){if(this.config.panning&&this.pressed&&!(this.config.panning=="avoid nodes"&&(this.dom?this.isLabel(a,c):b.getNode()))){var a=this.pos,b=b.getPos(),d=this.canvas,e=d.translateOffsetX,f=d.translateOffsetY,c=d.scaleOffsetX,d=d.scaleOffsetY;b.x*=c;b.y*=d;b.x+=e;b.y+=f;e=b.x-a.x;a=b.y-a.y;this.pos=b;this.canvas.translate(e*1/c,a*1/d)}},onMouseUp:function(){if(this.config.panning)this.pressed=!1}});var s;(function(){function a(a,
c){var f=document.createElement(a),g;for(g in c)typeof c[g]=="object"?h.extend(f[g],c[g]):f[g]=c[g];a=="canvas"&&!b&&G_vmlCanvasManager&&(f=G_vmlCanvasManager.initElement(document.body.appendChild(f)));return f}var c=typeof HTMLCanvasElement,b=c=="object"||c=="function";$jit.Canvas=s=new l({canvases:[],pos:!1,element:!1,labelContainer:!1,translateOffsetX:0,translateOffsetY:0,scaleOffsetX:1,scaleOffsetY:1,initialize:function(d,b){this.viz=d;this.opt=this.config=b;var c=h.type(b.injectInto)=="string"?
b.injectInto:b.injectInto.id,g=b.type,i=c+"-label",j=h(c),k=b.width||j.offsetWidth,m=b.height||j.offsetHeight;this.id=c;var n={injectInto:c,width:k,height:m};this.element=a("div",{id:c+"-canvaswidget",style:{position:"relative",width:k+"px",height:m+"px"}});this.labelContainer=this.createLabelContainer(b.Label.type,i,n);this.canvases.push(new s.Base[g]({config:h.extend({idSuffix:"-canvas"},n),plot:function(){d.fx.plot()},resize:function(){d.refresh()}}));if(c=b.background)n=new s.Background[c.type](d,
h.extend(c,n)),this.canvases.push(new s.Base[g](n));for(g=this.canvases.length;g--;)this.element.appendChild(this.canvases[g].canvas),g>0&&this.canvases[g].plot();this.element.appendChild(this.labelContainer);j.appendChild(this.element);var p=null,z=this;h.addEvent(window,"scroll",function(){clearTimeout(p);p=setTimeout(function(){z.getPos(!0)},500)})},getCtx:function(a){return this.canvases[a||0].getCtx()},getConfig:function(){return this.opt},getElement:function(){return this.element},getSize:function(a){return this.canvases[a||
0].getSize()},resize:function(a,b){this.getPos(!0);this.translateOffsetX=this.translateOffsetY=0;this.scaleOffsetX=this.scaleOffsetY=1;for(var c=0,g=this.canvases.length;c<g;c++)this.canvases[c].resize(a,b);c=this.element.style;c.width=a+"px";c.height=b+"px";if(this.labelContainer)this.labelContainer.style.width=a+"px"},translate:function(a,b,c){this.translateOffsetX+=a*this.scaleOffsetX;this.translateOffsetY+=b*this.scaleOffsetY;for(var g=0,i=this.canvases.length;g<i;g++)this.canvases[g].translate(a,
b,c)},scale:function(a,b){var c=this.scaleOffsetX*a,g=this.scaleOffsetY*b,i=this.translateOffsetX*(a-1)/c,h=this.translateOffsetY*(b-1)/g;this.scaleOffsetX=c;this.scaleOffsetY=g;c=0;for(g=this.canvases.length;c<g;c++)this.canvases[c].scale(a,b,!0);this.translate(i,h,!1)},getPos:function(a){if(a||!this.pos)return this.pos=h.getPos(this.getElement());return this.pos},clear:function(a){this.canvases[a||0].clear()},path:function(a,b){var c=this.canvases[0].getCtx();c.beginPath();b(c);c[a]();c.closePath()},
createLabelContainer:function(d,c,b){if(d=="HTML"||d=="Native")return a("div",{id:c,style:{overflow:"visible",position:"absolute",top:0,left:0,width:b.width+"px",height:0}});else if(d=="SVG"){d=document.createElementNS("http://www.w3.org/2000/svg","svg:svg");d.setAttribute("width",b.width);d.setAttribute("height",b.height);var g=d.style;g.position="absolute";g.left=g.top="0px";g=document.createElementNS("http://www.w3.org/2000/svg","svg:g");g.setAttribute("width",b.width);g.setAttribute("height",
b.height);g.setAttribute("x",0);g.setAttribute("y",0);g.setAttribute("id",c);d.appendChild(g);return d}}});s.Base={};s.Base["2D"]=new l({translateOffsetX:0,translateOffsetY:0,scaleOffsetX:1,scaleOffsetY:1,initialize:function(a){this.viz=a;this.opt=a.config;this.size=!1;this.createCanvas();this.translateToCenter()},createCanvas:function(){var d=this.opt,b=d.width,c=d.height;this.canvas=a("canvas",{id:d.injectInto+d.idSuffix,width:b,height:c,style:{position:"absolute",top:0,left:0,width:b+"px",height:c+
"px"}})},getCtx:function(){if(!this.ctx)return this.ctx=this.canvas.getContext("2d");return this.ctx},getSize:function(){if(this.size)return this.size;var a=this.canvas;return this.size={width:a.width,height:a.height}},translateToCenter:function(a){var b=this.getSize(),c=a?b.width-a.width-this.translateOffsetX*2:b.width;height=a?b.height-a.height-this.translateOffsetY*2:b.height;b=this.getCtx();a&&b.scale(1/this.scaleOffsetX,1/this.scaleOffsetY);b.translate(c/2,height/2)},resize:function(a,c){var f=
this.getSize(),g=this.canvas,i=g.style;this.size=!1;g.width=a;g.height=c;i.width=a+"px";i.height=c+"px";b?this.translateToCenter():this.translateToCenter(f);this.translateOffsetX=this.translateOffsetY=0;this.scaleOffsetX=this.scaleOffsetY=1;this.clear();this.viz.resize(a,c,this)},translate:function(a,b,c){var g=this.scaleOffsetY;this.translateOffsetX+=a*this.scaleOffsetX;this.translateOffsetY+=b*g;this.getCtx().translate(a,b);!c&&this.plot()},scale:function(a,b,c){this.scaleOffsetX*=a;this.scaleOffsetY*=
b;this.getCtx().scale(a,b);!c&&this.plot()},clear:function(){var a=this.getSize(),b=this.translateOffsetX,c=this.translateOffsetY,g=this.scaleOffsetX,i=this.scaleOffsetY;this.getCtx().clearRect((-a.width/2-b)*1/g,(-a.height/2-c)*1/i,a.width*1/g,a.height*1/i)},plot:function(){this.clear();this.viz.plot(this)}});s.Background={};s.Background.Circles=new l({initialize:function(a,b){this.viz=a;this.config=h.merge({idSuffix:"-bkcanvas",levelDistance:100,numberOfCircles:6,CanvasStyles:{},offset:0},b)},resize:function(a,
b,c){this.plot(c)},plot:function(a){var a=a.getCtx(),b=this.config,c=b.CanvasStyles,g;for(g in c)a[g]=c[g];g=b.numberOfCircles;b=b.levelDistance;for(c=1;c<=g;c++)a.beginPath(),a.arc(0,0,b*c,0,2*Math.PI,!1),a.stroke(),a.closePath()}})})();var x=function(a,c){this.theta=a||0;this.rho=c||0};$jit.Polar=x;x.prototype={getc:function(a){return this.toComplex(a)},getp:function(){return this},set:function(a){a=a.getp();this.theta=a.theta;this.rho=a.rho},setc:function(a,c){this.rho=Math.sqrt(a*a+c*c);this.theta=
Math.atan2(c,a);this.theta<0&&(this.theta+=Math.PI*2)},setp:function(a,c){this.theta=a;this.rho=c},clone:function(){return new x(this.theta,this.rho)},toComplex:function(a){var c=Math.cos(this.theta)*this.rho,b=Math.sin(this.theta)*this.rho;if(a)return{x:c,y:b};return new r(c,b)},add:function(a){return new x(this.theta+a.theta,this.rho+a.rho)},scale:function(a){return new x(this.theta,this.rho*a)},equals:function(a){return this.theta==a.theta&&this.rho==a.rho},$add:function(a){this.theta+=a.theta;
this.rho+=a.rho;return this},$madd:function(a){this.theta=(this.theta+a.theta)%(Math.PI*2);this.rho+=a.rho;return this},$scale:function(a){this.rho*=a;return this},isZero:function(){var a=Math.abs;return a(this.theta)<1.0E-4&&a(this.rho)<1.0E-4},interpolate:function(a,c){var b=Math.PI,d=b*2,e=function(a){return a<0?a%d+d:a%d},f=this.theta,g=a.theta,i=Math.abs(f-g);return{theta:i==b?f>g?e(g+(f-d-g)*c):e(g-d+(f-g)*c):i>=b?f>g?e(g+(f-d-g)*c):e(g-d+(f-(g-d))*c):e(g+(f-g)*c),rho:(this.rho-a.rho)*c+a.rho}}};
x.KER=new x(0,0);var r=function(a,c){this.x=a||0;this.y=c||0};$jit.Complex=r;r.prototype={getc:function(){return this},getp:function(a){return this.toPolar(a)},set:function(a){a=a.getc(!0);this.x=a.x;this.y=a.y},setc:function(a,c){this.x=a;this.y=c},setp:function(a,c){this.x=Math.cos(a)*c;this.y=Math.sin(a)*c},clone:function(){return new r(this.x,this.y)},toPolar:function(a){var c=this.norm(),b=Math.atan2(this.y,this.x);b<0&&(b+=Math.PI*2);if(a)return{theta:b,rho:c};return new x(b,c)},norm:function(){return Math.sqrt(this.squaredNorm())},
squaredNorm:function(){return this.x*this.x+this.y*this.y},add:function(a){return new r(this.x+a.x,this.y+a.y)},prod:function(a){return new r(this.x*a.x-this.y*a.y,this.y*a.x+this.x*a.y)},conjugate:function(){return new r(this.x,-this.y)},scale:function(a){return new r(this.x*a,this.y*a)},equals:function(a){return this.x==a.x&&this.y==a.y},$add:function(a){this.x+=a.x;this.y+=a.y;return this},$prod:function(a){var c=this.x,b=this.y;this.x=c*a.x-b*a.y;this.y=b*a.x+c*a.y;return this},$conjugate:function(){this.y=
-this.y;return this},$scale:function(a){this.x*=a;this.y*=a;return this},$div:function(a){var c=this.x,b=this.y,d=a.squaredNorm();this.x=c*a.x+b*a.y;this.y=b*a.x-c*a.y;return this.$scale(1/d)},isZero:function(){var a=Math.abs;return a(this.x)<1.0E-4&&a(this.y)<1.0E-4}};var G=function(a,c){return new r(a,c)};r.KER=G(0,0);$jit.Graph=new l({initialize:function(a,c,b,d){var e={klass:r,Node:{}};this.Node=c;this.Edge=b;this.Label=d;this.opt=h.merge(e,a||{});this.nodes={};this.edges={};var f=this;this.nodeList=
{};for(var g in H)f.nodeList[g]=function(a){return function(){var d=Array.prototype.slice.call(arguments);f.eachNode(function(b){b[a].apply(b,d)})}}(g)},getNode:function(a){if(this.hasNode(a))return this.nodes[a];return!1},get:function(a){return this.getNode(a)},getByName:function(a){for(var c in this.nodes){var b=this.nodes[c];if(b.name==a)return b}return!1},getAdjacence:function(a,c){if(a in this.edges)return this.edges[a][c];return!1},addNode:function(a){if(!this.nodes[a.id]){var c=this.edges[a.id]=
{};this.nodes[a.id]=new o.Node(h.extend({id:a.id,name:a.name,data:h.merge(a.data||{},{}),adjacencies:c},this.opt.Node),this.opt.klass,this.Node,this.Edge,this.Label)}return this.nodes[a.id]},addAdjacence:function(a,c,b){this.hasNode(a.id)||this.addNode(a);this.hasNode(c.id)||this.addNode(c);a=this.nodes[a.id];c=this.nodes[c.id];if(!a.adjacentTo(c)){var d=this.edges[a.id]=this.edges[a.id]||{},e=this.edges[c.id]=this.edges[c.id]||{};d[c.id]=e[a.id]=new o.Adjacence(a,c,b,this.Edge,this.Label);return d[c.id]}return this.edges[a.id][c.id]},
removeNode:function(a){if(this.hasNode(a)){delete this.nodes[a];var c=this.edges[a],b;for(b in c)delete this.edges[b][a];delete this.edges[a]}},removeAdjacence:function(a,c){delete this.edges[a][c];delete this.edges[c][a]},hasNode:function(a){return a in this.nodes},empty:function(){this.nodes={};this.edges={}}});var o=$jit.Graph,H;(function(){var a=function(a,b,c,g,i){var h,c=c||"current";if(c=="current")h=this.data;else if(c=="start")h=this.startData;else if(c=="end")h=this.endData;a="$"+(a?a+"-":
"")+b;if(g)return h[a];if(!this.Config.overridable)return i[b]||0;return a in h?h[a]:a in this.data?this.data[a]:i[b]||0},c=function(a,b,c,g){var g=g||"current",h;if(g=="current")h=this.data;else if(g=="start")h=this.startData;else if(g=="end")h=this.endData;h["$"+(a?a+"-":"")+b]=c},b=function(a,b){var a="$"+(a?a+"-":""),c=this;h.each(b,function(b){b=a+b;delete c.data[b];delete c.endData[b];delete c.startData[b]})};H={getData:function(b,c,f){return a.call(this,"",b,c,f,this.Config)},setData:function(a,
b,f){c.call(this,"",a,b,f)},setDataset:function(a,b){var a=h.splat(a),c;for(c in b)for(var g=0,i=h.splat(b[c]),j=a.length;g<j;g++)this.setData(c,i[g],a[g])},removeData:function(){b.call(this,"",Array.prototype.slice.call(arguments))},getCanvasStyle:function(b,c,f){return a.call(this,"canvas",b,c,f,this.Config.CanvasStyles)},setCanvasStyle:function(a,b,f){c.call(this,"canvas",a,b,f)},setCanvasStyles:function(a,b){var a=h.splat(a),c;for(c in b)for(var g=0,i=h.splat(b[c]),j=a.length;g<j;g++)this.setCanvasStyle(c,
i[g],a[g])},removeCanvasStyle:function(){b.call(this,"canvas",Array.prototype.slice.call(arguments))},getLabelData:function(b,c,f){return a.call(this,"label",b,c,f,this.Label)},setLabelData:function(a,b,f){c.call(this,"label",a,b,f)},setLabelDataset:function(a,b){var a=h.splat(a),c;for(c in b)for(var g=0,i=h.splat(b[c]),j=a.length;g<j;g++)this.setLabelData(c,i[g],a[g])},removeLabelData:function(){b.call(this,"label",Array.prototype.slice.call(arguments))}}})();o.Node=new l({initialize:function(a,
c,b,d,e){c={id:"",name:"",data:{},startData:{},endData:{},adjacencies:{},selected:!1,drawn:!1,exist:!1,angleSpan:{begin:0,end:0},pos:new c,startPos:new c,endPos:new c};h.extend(this,h.extend(c,a));this.Config=this.Node=b;this.Edge=d;this.Label=e},adjacentTo:function(a){return a.id in this.adjacencies},getAdjacency:function(a){return this.adjacencies[a]},getPos:function(a){a=a||"current";if(a=="current")return this.pos;else if(a=="end")return this.endPos;else if(a=="start")return this.startPos},setPos:function(a,
c){var c=c||"current",b;if(c=="current")b=this.pos;else if(c=="end")b=this.endPos;else if(c=="start")b=this.startPos;b.set(a)}});o.Node.implement(H);o.Adjacence=new l({initialize:function(a,c,b,d,e){this.nodeFrom=a;this.nodeTo=c;this.data=b||{};this.startData={};this.endData={};this.Config=this.Edge=d;this.Label=e}});o.Adjacence.implement(H);o.Util={filter:function(a){if(!a||h.type(a)!="string")return function(){return!0};var c=a.split(" ");return function(a){for(var d=0;d<c.length;d++)if(a[c[d]])return!1;
return!0}},getNode:function(a,c){return a.nodes[c]},eachNode:function(a,c,b){var b=this.filter(b),d;for(d in a.nodes)b(a.nodes[d])&&c(a.nodes[d])},each:function(a,c,b){this.eachNode(a,c,b)},eachAdjacency:function(a,c,b){var d=a.adjacencies,b=this.filter(b),e;for(e in d){var f=d[e];if(b(f)){if(f.nodeFrom!=a){var g=f.nodeFrom;f.nodeFrom=f.nodeTo;f.nodeTo=g}c(f,e)}}},computeLevels:function(a,c,b,d){var b=b||0,e=this.filter(d);this.eachNode(a,function(a){a._flag=!1;a._depth=-1},d);a=a.getNode(c);a._depth=
b;for(var f=[a];f.length!=0;){var g=f.pop();g._flag=!0;this.eachAdjacency(g,function(a){a=a.nodeTo;if(a._flag==!1&&e(a)){if(a._depth<0)a._depth=g._depth+1+b;f.unshift(a)}},d)}},eachBFS:function(a,c,b,d){var e=this.filter(d);this.clean(a);for(var f=[a.getNode(c)];f.length!=0;)a=f.pop(),a._flag=!0,b(a,a._depth),this.eachAdjacency(a,function(a){a=a.nodeTo;if(a._flag==!1&&e(a))a._flag=!0,f.unshift(a)},d)},eachLevel:function(a,c,b,d,e){var f=a._depth,g=this.filter(e),h=this,b=b===!1?Number.MAX_VALUE-f:
b;(function k(a,b,c){var e=a._depth;e>=b&&e<=c&&g(a)&&d(a,e);e<c&&h.eachAdjacency(a,function(a){a=a.nodeTo;a._depth>e&&k(a,b,c)})})(a,c+f,b+f)},eachSubgraph:function(a,c,b){this.eachLevel(a,0,!1,c,b)},eachSubnode:function(a,c,b){this.eachLevel(a,1,1,c,b)},anySubnode:function(a,c,b){var d=!1,c=c||h.lambda(!0),e=h.type(c)=="string"?function(a){return a[c]}:c;this.eachSubnode(a,function(a){e(a)&&(d=!0)},b);return d},getSubnodes:function(a,c,b){var d=[],c=c||0,e;h.type(c)=="array"?(e=c[0],c=c[1]):(e=
c,c=Number.MAX_VALUE-a._depth);this.eachLevel(a,e,c,function(a){d.push(a)},b);return d},getParents:function(a){var c=[];this.eachAdjacency(a,function(b){b=b.nodeTo;b._depth<a._depth&&c.push(b)});return c},isDescendantOf:function(a,c){if(a.id==c)return!0;for(var b=this.getParents(a),d=!1,e=0;!d&&e<b.length;e++)d=d||this.isDescendantOf(b[e],c);return d},clean:function(a){this.eachNode(a,function(a){a._flag=!1})},getClosestNodeToOrigin:function(a,c,b){return this.getClosestNodeToPos(a,x.KER,c,b)},getClosestNodeToPos:function(a,
c,b,d){var e=null,b=b||"current",c=c&&c.getc(!0)||r.KER,f=function(a,b){var c=a.x-b.x,d=a.y-b.y;return c*c+d*d};this.eachNode(a,function(a){e=e==null||f(a.getPos(b).getc(!0),c)<f(e.getPos(b).getc(!0),c)?a:e},d);return e}};h.each(["get","getNode","each","eachNode","computeLevels","eachBFS","clean","getClosestNodeToPos","getClosestNodeToOrigin"],function(a){o.prototype[a]=function(){return o.Util[a].apply(o.Util,[this].concat(Array.prototype.slice.call(arguments)))}});h.each(["eachAdjacency","eachLevel",
"eachSubgraph","eachSubnode","anySubnode","getSubnodes","getParents","isDescendantOf"],function(a){o.Node.prototype[a]=function(){return o.Util[a].apply(o.Util,[this].concat(Array.prototype.slice.call(arguments)))}});o.Op={options:{type:"nothing",duration:2E3,hideLabels:!0,fps:30},initialize:function(a){this.viz=a},removeNode:function(a,c){var b=this.viz,d=h.merge(this.options,b.controller,c),e=h.splat(a),f,g,i;switch(d.type){case "nothing":for(f=0;f<e.length;f++)b.graph.removeNode(e[f]);break;case "replot":this.removeNode(e,
{type:"nothing"});b.labels.clearLabels();b.refresh(!0);break;case "fade:seq":case "fade":g=this;for(f=0;f<e.length;f++)i=b.graph.getNode(e[f]),i.setData("alpha",0,"end");b.fx.animate(h.merge(d,{modes:["node-property:alpha"],onComplete:function(){g.removeNode(e,{type:"nothing"});b.labels.clearLabels();b.reposition();b.fx.animate(h.merge(d,{modes:["linear"]}))}}));break;case "fade:con":g=this;for(f=0;f<e.length;f++)i=b.graph.getNode(e[f]),i.setData("alpha",0,"end"),i.ignore=!0;b.reposition();b.fx.animate(h.merge(d,
{modes:["node-property:alpha","linear"],onComplete:function(){g.removeNode(e,{type:"nothing"});d.onComplete&&d.onComplete()}}));break;case "iter":g=this;b.fx.sequence({condition:function(){return e.length!=0},step:function(){g.removeNode(e.shift(),{type:"nothing"});b.labels.clearLabels()},onComplete:function(){d.onComplete&&d.onComplete()},duration:Math.ceil(d.duration/e.length)});break;default:this.doError()}},removeEdge:function(a,c){var b=this.viz,d=h.merge(this.options,b.controller,c),e=h.type(a[0])==
"string"?[a]:a,f,g,i;switch(d.type){case "nothing":for(f=0;f<e.length;f++)b.graph.removeAdjacence(e[f][0],e[f][1]);break;case "replot":this.removeEdge(e,{type:"nothing"});b.refresh(!0);break;case "fade:seq":case "fade":g=this;for(f=0;f<e.length;f++)(i=b.graph.getAdjacence(e[f][0],e[f][1]))&&i.setData("alpha",0,"end");b.fx.animate(h.merge(d,{modes:["edge-property:alpha"],onComplete:function(){g.removeEdge(e,{type:"nothing"});b.reposition();b.fx.animate(h.merge(d,{modes:["linear"]}))}}));break;case "fade:con":g=
this;for(f=0;f<e.length;f++)if(i=b.graph.getAdjacence(e[f][0],e[f][1]))i.setData("alpha",0,"end"),i.ignore=!0;b.reposition();b.fx.animate(h.merge(d,{modes:["edge-property:alpha","linear"],onComplete:function(){g.removeEdge(e,{type:"nothing"});d.onComplete&&d.onComplete()}}));break;case "iter":g=this;b.fx.sequence({condition:function(){return e.length!=0},step:function(){g.removeEdge(e.shift(),{type:"nothing"});b.labels.clearLabels()},onComplete:function(){d.onComplete()},duration:Math.ceil(d.duration/
e.length)});break;default:this.doError()}},sum:function(a,c){var b=this.viz,d=h.merge(this.options,b.controller,c),e=b.root,f;b.root=c.id||b.root;switch(d.type){case "nothing":f=b.construct(a);f.eachNode(function(a){a.eachAdjacency(function(a){b.graph.addAdjacence(a.nodeFrom,a.nodeTo,a.data)})});break;case "replot":b.refresh(!0);this.sum(a,{type:"nothing"});b.refresh(!0);break;case "fade:seq":case "fade":case "fade:con":that=this;f=b.construct(a);var g=!this.preprocessSum(f)?["node-property:alpha"]:
["node-property:alpha","edge-property:alpha"];b.reposition();d.type!="fade:con"?b.fx.animate(h.merge(d,{modes:["linear"],onComplete:function(){b.fx.animate(h.merge(d,{modes:g,onComplete:function(){d.onComplete()}}))}})):(b.graph.eachNode(function(a){a.id!=e&&a.pos.isZero()&&(a.pos.set(a.endPos),a.startPos.set(a.endPos))}),b.fx.animate(h.merge(d,{modes:["linear"].concat(g)})));break;default:this.doError()}},morph:function(a,c,b){var b=b||{},d=this.viz,e=h.merge(this.options,d.controller,c),f=d.root,
g;d.root=c.id||d.root;switch(e.type){case "nothing":g=d.construct(a);g.eachNode(function(a){var b=d.graph.hasNode(a.id);a.eachAdjacency(function(a){var b=!!d.graph.getAdjacence(a.nodeFrom.id,a.nodeTo.id);d.graph.addAdjacence(a.nodeFrom,a.nodeTo,a.data);if(b){var b=d.graph.getAdjacence(a.nodeFrom.id,a.nodeTo.id),c;for(c in a.data||{})b.data[c]=a.data[c]}});if(b){var b=d.graph.getNode(a.id),c;for(c in a.data||{})b.data[c]=a.data[c]}});d.graph.eachNode(function(a){a.eachAdjacency(function(a){g.getAdjacence(a.nodeFrom.id,
a.nodeTo.id)||d.graph.removeAdjacence(a.nodeFrom.id,a.nodeTo.id)});g.hasNode(a.id)||d.graph.removeNode(a.id)});break;case "replot":d.labels.clearLabels(!0);this.morph(a,{type:"nothing"});d.refresh(!0);d.refresh(!0);break;case "fade:seq":case "fade":case "fade:con":that=this;g=d.construct(a);var i="node-property"in b&&h.map(h.splat(b["node-property"]),function(a){return"$"+a});d.graph.eachNode(function(a){var b=g.getNode(a.id);if(b){var b=b.data,c;for(c in b)i&&h.indexOf(i,c)>-1?a.endData[c]=b[c]:
a.data[c]=b[c]}else a.setData("alpha",1),a.setData("alpha",1,"start"),a.setData("alpha",0,"end"),a.ignore=!0});d.graph.eachNode(function(a){a.ignore||a.eachAdjacency(function(a){if(!a.nodeFrom.ignore&&!a.nodeTo.ignore){var b=g.getNode(a.nodeFrom.id),a=g.getNode(a.nodeTo.id);b.adjacentTo(a)||(a=d.graph.getAdjacence(b.id,a.id),j=!0,a.setData("alpha",1),a.setData("alpha",1,"start"),a.setData("alpha",0,"end"))}})});var j=this.preprocessSum(g),a=!j?["node-property:alpha"]:["node-property:alpha","edge-property:alpha"];
a[0]+="node-property"in b?":"+h.splat(b["node-property"]).join(":"):"";a[1]=(a[1]||"edge-property:alpha")+("edge-property"in b?":"+h.splat(b["edge-property"]).join(":"):"");"label-property"in b&&a.push("label-property:"+h.splat(b["label-property"]).join(":"));d.reposition?d.reposition():d.compute("end");d.graph.eachNode(function(a){a.id!=f&&a.pos.getp().equals(x.KER)&&(a.pos.set(a.endPos),a.startPos.set(a.endPos))});d.fx.animate(h.merge(e,{modes:[b.position||"polar"].concat(a),onComplete:function(){d.graph.eachNode(function(a){a.ignore&&
d.graph.removeNode(a.id)});d.graph.eachNode(function(a){a.eachAdjacency(function(a){a.ignore&&d.graph.removeAdjacence(a.nodeFrom.id,a.nodeTo.id)})});e.onComplete()}}))}},contract:function(a,c){var b=this.viz;if(!a.collapsed&&a.anySubnode(h.lambda(!0)))c=h.merge(this.options,b.config,c||{},{modes:["node-property:alpha:span","linear"]}),a.collapsed=!0,function e(a){a.eachSubnode(function(a){a.ignore=!0;a.setData("alpha",0,c.type=="animate"?"end":"current");e(a)})}(a),c.type=="animate"?(b.compute("end"),
b.rotated&&b.rotate(b.rotated,"none",{property:"end"}),function f(b){b.eachSubnode(function(b){b.setPos(a.getPos("end"),"end");f(b)})}(a),b.fx.animate(c)):c.type=="replot"&&b.refresh()},expand:function(a,c){if("collapsed"in a){var b=this.viz,c=h.merge(this.options,b.config,c||{},{modes:["node-property:alpha:span","linear"]});delete a.collapsed;(function e(a){a.eachSubnode(function(a){delete a.ignore;a.setData("alpha",1,c.type=="animate"?"end":"current");e(a)})})(a);c.type=="animate"?(b.compute("end"),
b.rotated&&b.rotate(b.rotated,"none",{property:"end"}),b.fx.animate(c)):c.type=="replot"&&b.refresh()}},preprocessSum:function(a){var c=this.viz;a.eachNode(function(a){c.graph.hasNode(a.id)||(c.graph.addNode(a),a=c.graph.getNode(a.id),a.setData("alpha",0),a.setData("alpha",0,"start"),a.setData("alpha",1,"end"))});var b=!1;a.eachNode(function(a){a.eachAdjacency(function(a){var d=c.graph.getNode(a.nodeFrom.id),g=c.graph.getNode(a.nodeTo.id);d.adjacentTo(g)||(a=c.graph.addAdjacence(d,g,a.data),d.startAlpha==
d.endAlpha&&g.startAlpha==g.endAlpha&&(b=!0,a.setData("alpha",0),a.setData("alpha",0,"start"),a.setData("alpha",1,"end")))})});return b}};var K={none:{render:h.empty,contains:h.lambda(!1)},circle:{render:function(a,c,b,d){d=d.getCtx();d.beginPath();d.arc(c.x,c.y,b,0,Math.PI*2,!0);d.closePath();d[a]()},contains:function(a,c,b){var d=a.x-c.x,a=a.y-c.y;return d*d+a*a<=b*b}},ellipse:{render:function(a,c,b,d,e){var e=e.getCtx(),f=1,g=1,h=1,j=1,k=0;b>d?(k=b/2,g=d/b,j=b/d):(k=d/2,f=b/d,h=d/b);e.save();e.scale(f,
g);e.beginPath();e.arc(c.x*h,c.y*j,k,0,Math.PI*2,!0);e.closePath();e[a]();e.restore()},contains:function(a,c,b,d){var e=0,f=1,g=1,h=0,j=0,e=0;b>d?(e=b/2,g=d/b):(e=d/2,f=b/d);h=(a.x-c.x)*(1/f);j=(a.y-c.y)*(1/g);return h*h+j*j<=e*e}},square:{render:function(a,c,b,d){d.getCtx()[a+"Rect"](c.x-b,c.y-b,2*b,2*b)},contains:function(a,c,b){return Math.abs(c.x-a.x)<=b&&Math.abs(c.y-a.y)<=b}},rectangle:{render:function(a,c,b,d,e){e.getCtx()[a+"Rect"](c.x-b/2,c.y-d/2,b,d)},contains:function(a,c,b,d){return Math.abs(c.x-
a.x)<=b/2&&Math.abs(c.y-a.y)<=d/2}},triangle:{render:function(a,c,b,d){var d=d.getCtx(),e=c.x,f=c.y-b,g=e-b,c=c.y+b,b=e+b;d.beginPath();d.moveTo(e,f);d.lineTo(g,c);d.lineTo(b,c);d.closePath();d[a]()},contains:function(a,c,b){return K.circle.contains(a,c,b)}},star:{render:function(a,c,b,d){var d=d.getCtx(),e=Math.PI/5;d.save();d.translate(c.x,c.y);d.beginPath();d.moveTo(b,0);for(c=0;c<9;c++)d.rotate(e),c%2==0?d.lineTo(b/0.525731*0.200811,0):d.lineTo(b,0);d.closePath();d[a]();d.restore()},contains:function(a,
c,b){return K.circle.contains(a,c,b)}}},M={line:{render:function(a,c,b){b=b.getCtx();b.beginPath();b.moveTo(a.x,a.y);b.lineTo(c.x,c.y);b.stroke()},contains:function(a,c,b,d){var e=Math.min,f=Math.max,g=e(a.x,c.x),h=f(a.x,c.x),e=e(a.y,c.y),f=f(a.y,c.y);if(b.x>=g&&b.x<=h&&b.y>=e&&b.y<=f){if(Math.abs(c.x-a.x)<=d)return!0;return Math.abs((c.y-a.y)/(c.x-a.x)*(b.x-a.x)+a.y-b.y)<=d}return!1}},arrow:{render:function(a,c,b,d,e){e=e.getCtx();d&&(d=a,a=c,c=d);d=new r(c.x-a.x,c.y-a.y);d.$scale(b/d.norm());var b=
new r(c.x-d.x,c.y-d.y),f=new r(-d.y/2,d.x/2),d=b.add(f),b=b.$add(f.$scale(-1));e.beginPath();e.moveTo(a.x,a.y);e.lineTo(c.x,c.y);e.stroke();e.beginPath();e.moveTo(d.x,d.y);e.lineTo(b.x,b.y);e.lineTo(c.x,c.y);e.closePath();e.fill()},contains:function(a,c,b,d){return M.line.contains(a,c,b,d)}},hyperline:{render:function(a,c,b,d){function e(a,b){return a<b?a+Math.PI>b?!1:!0:b+Math.PI>a?!0:!1}var d=d.getCtx(),f=function(a,b){var c=a.x*b.y-a.y*b.x,d=a.squaredNorm(),e=b.squaredNorm();if(c==0)return{x:0,
y:0,ratio:-1};var f=(a.y*e-b.y*d+a.y-b.y)/c,c=(b.x*d-a.x*e+b.x-a.x)/c,d=(f*f+c*c)/4-1;if(d<0)return{x:0,y:0,ratio:-1};d=Math.sqrt(d);return{x:-f/2,y:-c/2,ratio:d>1E3?-1:d,a:f,b:c}}(a,c);f.a>1E3||f.b>1E3||f.ratio<0?(d.beginPath(),d.moveTo(a.x*b,a.y*b),d.lineTo(c.x*b,c.y*b)):(c=Math.atan2(c.y-f.y,c.x-f.x),a=Math.atan2(a.y-f.y,a.x-f.x),e=e(c,a),d.beginPath(),d.arc(f.x*b,f.y*b,f.ratio*b,c,a,e));d.stroke()},contains:h.lambda(!1)}};o.Plot={initialize:function(a,c){this.viz=a;this.config=a.config;this.node=
a.config.Node;this.edge=a.config.Edge;this.animation=new J;this.nodeTypes=new c.Plot.NodeTypes;this.edgeTypes=new c.Plot.EdgeTypes;this.labels=a.labels},nodeHelper:K,edgeHelper:M,Interpolator:{map:{border:"color",color:"color",width:"number",height:"number",dim:"number",alpha:"number",lineWidth:"number",angularWidth:"number",span:"number",valueArray:"array-number",dimArray:"array-number"},canvas:{globalAlpha:"number",fillStyle:"color",strokeStyle:"color",lineWidth:"number",shadowBlur:"number",shadowColor:"color",
shadowOffsetX:"number",shadowOffsetY:"number",miterLimit:"number"},label:{size:"number",color:"color"},compute:function(a,c,b){return a+(c-a)*b},moebius:function(a,c,b,d){c=d.scale(-b);if(c.norm()<1){var b=c.x,d=c.y,e=a.startPos.getc().moebiusTransformation(c);a.pos.setc(e.x,e.y);c.x=b;c.y=d}},linear:function(a,c,b){var c=a.startPos.getc(!0),d=a.endPos.getc(!0);a.pos.setc(this.compute(c.x,d.x,b),this.compute(c.y,d.y,b))},polar:function(a,c,b){c=a.startPos.getp(!0);b=a.endPos.getp().interpolate(c,
b);a.pos.setp(b.theta,b.rho)},number:function(a,c,b,d,e){var f=a[d](c,"start"),d=a[d](c,"end");a[e](c,this.compute(f,d,b))},color:function(a,c,b,d,e){var f=h.hexToRgb(a[d](c,"start")),d=h.hexToRgb(a[d](c,"end")),g=this.compute,b=h.rgbToHex([parseInt(g(f[0],d[0],b)),parseInt(g(f[1],d[1],b)),parseInt(g(f[2],d[2],b))]);a[e](c,b)},"array-number":function(a,c,b,d,e){for(var f=a[d](c,"start"),d=a[d](c,"end"),g=[],h=0,j=f.length;h<j;h++){var k=f[h],m=d[h];if(k.length){for(var n=0,p=k.length,z=[];n<p;n++)z.push(this.compute(k[n],
m[n],b));g.push(z)}else g.push(this.compute(k,m,b))}a[e](c,g)},node:function(a,c,b,d,e,f){d=this[d];if(c)for(var g=c.length,h=0;h<g;h++){var j=c[h];this[d[j]](a,j,b,e,f)}else for(j in d)this[d[j]](a,j,b,e,f)},edge:function(a,c,b,d,e,f){var a=a.adjacencies,g;for(g in a)this.node(a[g],c,b,d,e,f)},"node-property":function(a,c,b){this.node(a,c,b,"map","getData","setData")},"edge-property":function(a,c,b){this.edge(a,c,b,"map","getData","setData")},"label-property":function(a,c,b){this.node(a,c,b,"label",
"getLabelData","setLabelData")},"node-style":function(a,c,b){this.node(a,c,b,"canvas","getCanvasStyle","setCanvasStyle")},"edge-style":function(a,c,b){this.edge(a,c,b,"canvas","getCanvasStyle","setCanvasStyle")}},sequence:function(a){var c=this,a=h.merge({condition:h.lambda(!1),step:h.empty,onComplete:h.empty,duration:200},a||{}),b=setInterval(function(){a.condition()?a.step():(clearInterval(b),a.onComplete());c.viz.refresh(!0)},a.duration)},prepare:function(a){var c=this.viz.graph,b={"node-property":{getter:"getData",
setter:"setData"},"edge-property":{getter:"getData",setter:"setData"},"node-style":{getter:"getCanvasStyle",setter:"setCanvasStyle"},"edge-style":{getter:"getCanvasStyle",setter:"setCanvasStyle"}},d={};if(h.type(a)=="array")for(var e=0,f=a.length;e<f;e++){var g=a[e].split(":");d[g.shift()]=g}else for(e in a)e=="position"?d[a.position]=[]:d[e]=h.splat(a[e]);c.eachNode(function(a){a.startPos.set(a.pos);h.each(["node-property","node-style"],function(c){if(c in d)for(var e=d[c],f=0,g=e.length;f<g;f++)a[b[c].setter](e[f],
a[b[c].getter](e[f]),"start")});h.each(["edge-property","edge-style"],function(c){if(c in d){var e=d[c];a.eachAdjacency(function(a){for(var d=0,f=e.length;d<f;d++)a[b[c].setter](e[d],a[b[c].getter](e[d]),"start")})}})});return d},animate:function(a,c){var a=h.merge(this.viz.config,a||{}),b=this,d=this.viz.graph,e=this.Interpolator,f=a.type==="nodefx"?this.nodeFxAnimation:this.animation,g=this.prepare(a.modes);a.hideLabels&&this.labels.hideLabels(!0);f.setOptions(h.extend(a,{$animating:!1,compute:function(f){d.eachNode(function(a){for(var b in g)e[b](a,
g[b],f,c)});b.plot(a,this.$animating,f);this.$animating=!0},complete:function(){a.hideLabels&&b.labels.hideLabels(!1);b.plot(a);a.onComplete()}})).start()},nodeFx:function(a){var c=this.viz,b=c.graph,d=this.nodeFxAnimation,e=h.merge(this.viz.config,{elements:{id:!1,properties:{}},reposition:!1}),a=h.merge(e,a||{},{onBeforeCompute:h.empty,onAfterCompute:h.empty});d.stopTimer();var f=a.elements.properties;a.elements.id?(d=h.splat(a.elements.id),h.each(d,function(a){if(a=b.getNode(a))for(var c in f)a.setData(c,
f[c],"end")})):b.eachNode(function(a){for(var b in f)a.setData(b,f[b],"end")});var d=[],g;for(g in f)d.push(g);g=["node-property:"+d.join(":")];a.reposition&&(g.push("linear"),c.compute("end"));this.animate(h.merge(a,{modes:g,type:"nodefx"}))},plot:function(a,c){var b=this.viz,d=b.graph,e=b.canvas,b=b.root,f=this;e.getCtx();a=a||this.viz.controller;a.clearCanvas&&e.clear();if(b=d.getNode(b)){var g=!!b.visited;d.eachNode(function(b){var d=b.getData("alpha");b.eachAdjacency(function(d){var h=d.nodeTo;
!!h.visited===g&&b.drawn&&h.drawn&&(!c&&a.onBeforePlotLine(d),f.plotLine(d,e,c),!c&&a.onAfterPlotLine(d))});b.drawn&&(!c&&a.onBeforePlotNode(b),f.plotNode(b,e,c),!c&&a.onAfterPlotNode(b));!f.labelsHidden&&a.withLabels&&(b.drawn&&d>=0.95?f.labels.plotLabel(e,b,a):f.labels.hideLabel(b,!1));b.visited=!g})}},plotTree:function(a,c,b){var d=this,e=this.viz.canvas;e.getCtx();var f=a.getData("alpha");a.eachSubnode(function(f){if(c.plotSubtree(a,f)&&f.exist&&f.drawn){var h=a.getAdjacency(f.id);!b&&c.onBeforePlotLine(h);
d.plotLine(h,e,b);!b&&c.onAfterPlotLine(h);d.plotTree(f,c,b)}});a.drawn?(!b&&c.onBeforePlotNode(a),this.plotNode(a,e,b),!b&&c.onAfterPlotNode(a),!c.hideLabels&&c.withLabels&&f>=0.95?this.labels.plotLabel(e,a,c):this.labels.hideLabel(a,!1)):this.labels.hideLabel(a,!0)},plotNode:function(a,c,b){var d=a.getData("type"),e=this.node.CanvasStyles;if(d!="none"){var f=a.getData("lineWidth"),g=a.getData("color"),h=a.getData("alpha"),j=c.getCtx();j.save();j.lineWidth=f;j.fillStyle=j.strokeStyle=g;j.globalAlpha=
h;for(var k in e)j[k]=a.getCanvasStyle(k);this.nodeTypes[d].render.call(this,a,c,b);j.restore()}},plotLine:function(a,c,b){var d=a.getData("type"),e=this.edge.CanvasStyles;if(d!="none"){var f=a.getData("lineWidth"),g=a.getData("color"),h=c.getCtx(),j=a.nodeFrom,k=a.nodeTo;h.save();h.lineWidth=f;h.fillStyle=h.strokeStyle=g;h.globalAlpha=Math.min(j.getData("alpha"),k.getData("alpha"),a.getData("alpha"));for(var m in e)h[m]=a.getCanvasStyle(m);this.edgeTypes[d].render.call(this,a,c,b);h.restore()}}};
o.Plot3D=h.merge(o.Plot,{Interpolator:{linear:function(a,c,b){var c=a.startPos.getc(!0),d=a.endPos.getc(!0);a.pos.setc(this.compute(c.x,d.x,b),this.compute(c.y,d.y,b),this.compute(c.z,d.z,b))}},plotNode:function(a,c){a.getData("type")!="none"&&this.plotElement(a,c,{getAlpha:function(){return a.getData("alpha")}})},plotLine:function(a,c){a.getData("type")!="none"&&this.plotElement(a,c,{getAlpha:function(){return Math.min(a.nodeFrom.getData("alpha"),a.nodeTo.getData("alpha"),a.getData("alpha"))}})},
plotElement:function(a,c,b){var d=c.getCtx(),e=new Matrix4,f=c.config.Scene.Lighting,g=c.canvases[0],c=g.program,g=g.camera;if(!a.geometry)a.geometry=new (O3D[a.getData("type")]);a.geometry.update(a);if(!a.webGLVertexBuffer){for(var i=[],j=[],k=[],m=0,n=a.geometry,p=0,z=n.vertices,n=n.faces,Q=n.length;p<Q;p++){var q=n[p],l=z[q.a],o=z[q.b],B=z[q.c],w=q.d?z[q.d]:!1,q=q.normal;i.push(l.x,l.y,l.z);i.push(o.x,o.y,o.z);i.push(B.x,B.y,B.z);w&&i.push(w.x,w.y,w.z);k.push(q.x,q.y,q.z);k.push(q.x,q.y,q.z);k.push(q.x,
q.y,q.z);w&&k.push(q.x,q.y,q.z);j.push(m,m+1,m+2);w?(j.push(m,m+2,m+3),m+=4):m+=3}a.webGLVertexBuffer=d.createBuffer();d.bindBuffer(d.ARRAY_BUFFER,a.webGLVertexBuffer);d.bufferData(d.ARRAY_BUFFER,new Float32Array(i),d.STATIC_DRAW);a.webGLFaceBuffer=d.createBuffer();d.bindBuffer(d.ELEMENT_ARRAY_BUFFER,a.webGLFaceBuffer);d.bufferData(d.ELEMENT_ARRAY_BUFFER,new Uint16Array(j),d.STATIC_DRAW);a.webGLFaceCount=j.length;a.webGLNormalBuffer=d.createBuffer();d.bindBuffer(d.ARRAY_BUFFER,a.webGLNormalBuffer);
d.bufferData(d.ARRAY_BUFFER,new Float32Array(k),d.STATIC_DRAW)}e.multiply(g.matrix,a.geometry.matrix);d.uniformMatrix4fv(c.viewMatrix,!1,e.flatten());d.uniformMatrix4fv(c.projectionMatrix,!1,g.projectionMatrix.flatten());e=Matrix4.makeInvert(e);e.$transpose();d.uniformMatrix4fv(c.normalMatrix,!1,e.flatten());e=h.hexToRgb(a.getData("color"));e.push(b.getAlpha());d.uniform4f(c.color,e[0]/255,e[1]/255,e[2]/255,e[3]);d.uniform1i(c.enableLighting,f.enable);if(f.enable){if(f.ambient)b=f.ambient,d.uniform3f(c.ambientColor,
b[0],b[1],b[2]);if(f.directional)f=f.directional,e=f.color,f=f.direction,f=(new Vector3(f.x,f.y,f.z)).normalize().$scale(-1),d.uniform3f(c.lightingDirection,f.x,f.y,f.z),d.uniform3f(c.directionalColor,e[0],e[1],e[2])}d.bindBuffer(d.ARRAY_BUFFER,a.webGLVertexBuffer);d.vertexAttribPointer(c.position,3,d.FLOAT,!1,0,0);d.bindBuffer(d.ARRAY_BUFFER,a.webGLNormalBuffer);d.vertexAttribPointer(c.normal,3,d.FLOAT,!1,0,0);d.bindBuffer(d.ELEMENT_ARRAY_BUFFER,a.webGLFaceBuffer);d.drawElements(d.TRIANGLES,a.webGLFaceCount,
d.UNSIGNED_SHORT,0)}});o.Label={};o.Label.Native=new l({initialize:function(a){this.viz=a},plotLabel:function(a,c,b){var d=a.getCtx();c.pos.getc(!0);d.font=c.getLabelData("style")+" "+c.getLabelData("size")+"px "+c.getLabelData("family");d.textAlign=c.getLabelData("textAlign");d.fillStyle=d.strokeStyle=c.getLabelData("color");d.textBaseline=c.getLabelData("textBaseline");this.renderLabel(a,c,b)},renderLabel:function(a,c){var b=a.getCtx(),d=c.pos.getc(!0);b.fillText(c.name,d.x,d.y+c.getData("height")/
2)},hideLabel:h.empty,hideLabels:h.empty});o.Label.DOM=new l({labelsHidden:!1,labelContainer:!1,labels:{},getLabelContainer:function(){return this.labelContainer?this.labelContainer:this.labelContainer=document.getElementById(this.viz.config.labelContainer)},getLabel:function(a){return a in this.labels&&this.labels[a]!=null?this.labels[a]:this.labels[a]=document.getElementById(a)},hideLabels:function(a){this.getLabelContainer().style.display=a?"none":"";this.labelsHidden=a},clearLabels:function(a){for(var c in this.labels)if(a||
!this.viz.graph.hasNode(c))this.disposeLabel(c),delete this.labels[c]},disposeLabel:function(a){(a=this.getLabel(a))&&a.parentNode&&a.parentNode.removeChild(a)},hideLabel:function(a,c){var a=h.splat(a),b=c?"":"none",d=this;h.each(a,function(a){if(a=d.getLabel(a.id))a.style.display=b})},fitsInCanvas:function(a,c){var b=c.getSize();if(a.x>=b.width||a.x<0||a.y>=b.height||a.y<0)return!1;return!0}});o.Label.HTML=new l({Implements:o.Label.DOM,plotLabel:function(a,c,b){var a=c.id,d=this.getLabel(a);if(!d&&
!(d=document.getElementById(a))){var d=document.createElement("div"),e=this.getLabelContainer();d.id=a;d.className="node";d.style.position="absolute";b.onCreateLabel(d,c);e.appendChild(d);this.labels[c.id]=d}this.placeLabel(d,c,b)}});o.Label.SVG=new l({Implements:o.Label.DOM,plotLabel:function(a,c,b){var a=c.id,d=this.getLabel(a);if(!d&&!(d=document.getElementById(a))){var d=document.createElementNS("http://www.w3.org/2000/svg","svg:text"),e=document.createElementNS("http://www.w3.org/2000/svg","svg:tspan");
d.appendChild(e);e=this.getLabelContainer();d.setAttribute("id",a);d.setAttribute("class","node");e.appendChild(d);b.onCreateLabel(d,c);this.labels[c.id]=d}this.placeLabel(d,c,b)}});o.Geom=new l({initialize:function(a){this.viz=a;this.config=a.config;this.node=a.config.Node;this.edge=a.config.Edge},translate:function(a,c){c=h.splat(c);this.viz.graph.eachNode(function(b){h.each(c,function(c){b.getPos(c).$add(a)})})},setRightLevelToShow:function(a,c,b){var d=this.getRightLevelToShow(a,c),e=this.viz.labels,
f=h.merge({execShow:!0,execHide:!0,onHide:h.empty,onShow:h.empty},b||{});a.eachLevel(0,this.config.levelsToShow,function(b){if(b._depth-a._depth>d){if(f.onHide(b),f.execHide)b.drawn=!1,b.exist=!1,e.hideLabel(b,!1)}else if(f.onShow(b),f.execShow)b.exist=!0});a.drawn=!0},getRightLevelToShow:function(a,c){var b=this.config,d=b.levelsToShow;if(!b.constrained)return d;for(;!this.treeFitsInCanvas(a,c,d)&&d>1;)d--;return d}});var N={construct:function(a){var c=h.type(a)=="array",b=new o(this.graphOptions,
this.config.Node,this.config.Edge,this.config.Label);c?function(a,b){for(var c=function(c){for(var f=0,g=b.length;f<g;f++)if(b[f].id==c)return b[f];return a.addNode({id:c,name:c})},g=0,i=b.length;g<i;g++){a.addNode(b[g]);var j=b[g].adjacencies;if(j)for(var k=0,m=j.length;k<m;k++){var n=j[k],p={};if(typeof j[k]!="string")p=h.merge(n.data,{}),n=n.nodeTo;a.addAdjacence(b[g],c(n),p)}}}(b,a):function(a,b){a.addNode(b);if(b.children)for(var c=0,g=b.children;c<g.length;c++)a.addAdjacence(b,g[c]),arguments.callee(a,
g[c])}(b,a);return b},loadJSON:function(a,c){this.json=a;this.labels&&this.labels.clearLabels&&this.labels.clearLabels(!0);this.graph=this.construct(a);this.root=h.type(a)!="array"?a.id:a[c?c:0].id},toJSON:function(a){if((a||"tree")=="tree")var c={},c=function e(a){var b={};b.id=a.id;b.name=a.name;b.data=a.data;var c=[];a.eachSubnode(function(a){c.push(e(a))});b.children=c;return b}(this.graph.getNode(this.root));else{var c=[],b=!!this.graph.getNode(this.root).visited;this.graph.eachNode(function(a){var f=
{};f.id=a.id;f.name=a.name;f.data=a.data;var g=[];a.eachAdjacency(function(a){var c=a.nodeTo;if(!!c.visited===b){var e={};e.nodeTo=c.id;e.data=a.data;g.push(e)}});f.adjacencies=g;c.push(f);a.visited=!b})}return c}},I=$jit.Layouts={},O={label:null,compute:function(a,c,b){this.initializeLabel(b);var d=this.label,e=d.style;a.eachNode(function(a){var b=a.getData("autoWidth"),c=a.getData("autoHeight");if(b||c){delete a.data.$width;delete a.data.$height;delete a.data.$dim;var j=a.getData("width"),k=a.getData("height");
e.width=b?"auto":j+"px";e.height=c?"auto":k+"px";d.innerHTML=a.name;b=d.offsetWidth;c=d.offsetHeight;j=a.getData("type");h.indexOf(["circle","square","triangle","star"],j)===-1?(a.setData("width",b),a.setData("height",c)):(b=b>c?b:c,a.setData("width",b),a.setData("height",b),a.setData("dim",b))}})},initializeLabel:function(a){if(!this.label)this.label=document.createElement("div"),document.body.appendChild(this.label);this.setLabelStyles(a)},setLabelStyles:function(){h.extend(this.label.style,{visibility:"hidden",
position:"absolute",width:"auto",height:"auto"});this.label.className="jit-autoadjust-label"}};I.Tree=function(){function a(a,b,c,d,e){var f=b.Node,g=b.multitree;if(f.overridable){var h=-1,i=-1;a.eachNode(function(a){if(a._depth==c&&(!g||"$orn"in a.data&&a.data.$orn==d)){var b=a.getData("width",e),a=a.getData("height",e);h=h<b?b:h;i=i<a?a:i}});return{width:h<0?f.width:h,height:i<0?f.height:i}}else return f}function c(a,b,c,d){a.getPos(b)[d=="left"||d=="right"?"y":"x"]+=c}function b(a,b){var c=[];
h.each(a,function(a){a=m.call(a);a[0]+=b;a[1]+=b;c.push(a)});return c}function d(a,b){if(a.length==0)return b;if(b.length==0)return a;var c=a.shift(),e=b.shift();return[[c[0],e[1]]].concat(d(a,b))}function e(a,b){b=b||[];if(a.length==0)return b;var c=a.pop();return e(a,d(c,b))}function f(a,b,c,d,e){if(a.length<=e||b.length<=e)return 0;var g=a[e][1],h=b[e][0];return Math.max(f(a,b,c,d,++e)+c,g-h+d)}function g(a,c,e){function g(a,h,i){if(h.length<=i)return[];var j=h[i],n=f(a,j,c,e,0);return[n].concat(g(d(a,
b(j,n)),h,++i))}return g([],a,0)}function i(a,c,e){function g(a,h,i){if(h.length<=i)return[];var j=h[i],n=-f(j,a,c,e,0);return[n].concat(g(d(b(j,n),a),h,++i))}a=m.call(a);return g([],a.reverse(),0).reverse()}function j(a,b,c,d){var e=g(a,b,c),a=i(a,b,c);d=="left"?a=e:d=="right"&&(e=a);d=0;for(b=[];d<e.length;d++)b[d]=(e[d]+a[d])/2;return b}function k(d,f,g,h,i){function k(f,p,l){var o=f.getData(v,g),u=[],w=[],B=!1,C=(p||f.getData(A,g))+h.levelDistance;f.eachSubnode(function(b){if(b.exist&&(!m||"$orn"in
b.data&&b.data.$orn==i))B||(B=a(d,h,b._depth,i,g)),b=k(b,B[A],l+C),u.push(b.tree),w.push(b.extent)});for(var p=j(w,x,s,y),E=0,D=[];E<u.length;E++)c(u[E],g,p[E],i),D.push(b(w[E],p[E]));o=[[-o/2,o/2]].concat(e(D));f.getPos(g)[r]=0;i=="top"||i=="left"?f.getPos(g)[t]=l:f.getPos(g)[t]=-l;return{tree:f,extent:o}}var m=h.multitree,l=["x","y"],o=["width","height"],u=+(i=="left"||i=="right"),r=l[u],t=l[1-u],v=o[u],A=o[1-u],s=h.siblingOffset,x=h.subtreeOffset,y=h.align;k(f,!1,0)}var m=Array.prototype.slice;
return new l({compute:function(a,b){var c=a||"start",d=this.graph.getNode(this.root);h.extend(d,{drawn:!0,exist:!0,selected:!0});O.compute(this.graph,c,this.config);(b||!("_depth"in d))&&this.graph.computeLevels(this.root,0,"ignore");this.computePositions(d,c)},computePositions:function(a,b){var c=this.config,d=c.multitree,e=c.align,f=e!=="center"&&c.indent,c=c.orientation,g=this;h.each(d?["top","right","bottom","left"]:[c],function(c){k(g.graph,a,b,g.config,c,b);var h=["x","y"][+(c=="left"||c=="right")];
(function L(a){a.eachSubnode(function(g){if(g.exist&&(!d||"$orn"in g.data&&g.data.$orn==c))g.getPos(b)[h]+=a.getPos(b)[h],f&&(g.getPos(b)[h]+=e=="left"?f:-f),L(g)})})(a)})}})}();$jit.ST=function(){function a(a){a=a||this.clickedNode;if(!this.config.constrained)return[];var c=this.geom,f=this.canvas,g=a._depth,h=[];this.graph.eachNode(function(b){b.exist&&!b.selected&&(b.isDescendantOf(a.id)?b._depth<=g&&h.push(b):h.push(b))});c=c.getRightLevelToShow(a,f);a.eachLevel(c,c,function(a){a.exist&&!a.selected&&
h.push(a)});for(c=0;c<b.length;c++)f=this.graph.getNode(b[c]),f.isDescendantOf(a.id)||h.push(f);return h}function c(){var a=[],b=this.config;this.clickedNode.eachLevel(0,b.levelsToShow,function(c){b.multitree&&!("$orn"in c.data)&&c.anySubnode(function(a){return a.exist&&!a.drawn})?a.push(c):c.drawn&&!c.anySubnode("drawn")&&a.push(c)});return a}var b=[];return new l({Implements:[N,y,I.Tree],initialize:function(a){var b=$jit.ST,a=this.controller=this.config=h.merge(v("Canvas","Fx","Tree","Node","Edge",
"Controller","Tips","NodeStyles","Events","Navigation","Label"),{levelsToShow:2,levelDistance:30,constrained:!0,Node:{type:"rectangle"},duration:700,offsetX:0,offsetY:0},a);if(a.useCanvas)this.canvas=a.useCanvas,this.config.labelContainer=this.canvas.id+"-label";else{if(a.background)a.background=h.merge({type:"Circles"},a.background);this.canvas=new s(this,a);this.config.labelContainer=(typeof a.injectInto=="string"?a.injectInto:a.injectInto.id)+"-label"}this.graphOptions={klass:r};this.graph=new o(this.graphOptions,
this.config.Node,this.config.Edge);this.labels=new b.Label[a.Label.type](this);this.fx=new b.Plot(this,b);this.op=new b.Op(this);this.group=new b.Group(this);this.geom=new b.Geom(this);this.clickedNode=null;this.initializeExtras()},plot:function(){this.fx.plot(this.controller)},switchPosition:function(a,b,c){var g=this.geom,h=this.fx,j=this;if(!h.busy)h.busy=!0,this.contract({onComplete:function(){g.switchOrientation(a);j.compute("end",!1);h.busy=!1;if(b=="animate")j.onClick(j.clickedNode.id,c);else b==
"replot"&&j.select(j.clickedNode.id,c)}},a)},switchAlignment:function(a,b,c){this.config.align=a;if(b=="animate")this.select(this.clickedNode.id,c);else if(b=="replot")this.onClick(this.clickedNode.id,c)},addNodeInPath:function(a){b.push(a);this.select(this.clickedNode&&this.clickedNode.id||this.root)},clearNodesInPath:function(){b.length=0;this.select(this.clickedNode&&this.clickedNode.id||this.root)},refresh:function(){this.reposition();this.select(this.clickedNode&&this.clickedNode.id||this.root)},
reposition:function(){this.graph.computeLevels(this.root,0,"ignore");this.geom.setRightLevelToShow(this.clickedNode,this.canvas);this.graph.eachNode(function(a){if(a.exist)a.drawn=!0});this.compute("end")},requestNodes:function(a,b){var c=h.merge(this.controller,b),g=this.config.levelsToShow;if(c.request){var i=[],j=a._depth;a.eachLevel(0,g,function(a){if(a.drawn&&!a.anySubnode())i.push(a),a._level=g-(a._depth-j)});this.group.requestNodes(i,c)}else c.onComplete()},contract:function(b,c){var f=this.config.orientation,
g=this.geom,i=this.group;c&&g.switchOrientation(c);var j=a.call(this);c&&g.switchOrientation(f);i.contract(j,h.merge(this.controller,b))},move:function(a,b){this.compute("end",!1);var c=b.Move,g={x:c.offsetX,y:c.offsetY};c.enable&&this.geom.translate(a.endPos.add(g).$scale(-1),"end");this.fx.animate(h.merge(this.controller,{modes:["linear"]},b))},expand:function(a,b){this.group.expand(c.call(this,a),h.merge(this.controller,b))},selectPath:function(a){function c(a){if(!(a==null||a.selected))a.selected=
!0,h.each(f.group.getSiblings([a])[a.id],function(a){a.exist=!0;a.drawn=!0}),a=a.getParents(),a=a.length>0?a[0]:null,c(a)}var f=this;this.graph.eachNode(function(a){a.selected=!1});for(var g=0,a=[a.id].concat(b);g<a.length;g++)c(this.graph.getNode(a[g]))},setRoot:function(a,b,c){function g(){if(this.config.multitree&&m.data.$orn){var b={left:"right",right:"left",top:"bottom",bottom:"top"}[m.data.$orn];k.data.$orn=b;(function z(c){c.eachSubnode(function(c){if(c.id!=a)c.data.$orn=b,z(c)})})(k);delete m.data.$orn}this.root=
a;this.clickedNode=m;this.graph.computeLevels(this.root,0,"ignore");this.geom.setRightLevelToShow(m,j,{execHide:!1,onShow:function(a){if(!a.drawn)a.drawn=!0,a.setData("alpha",1,"end"),a.setData("alpha",0),a.pos.setc(m.pos.x,m.pos.y)}});this.compute("end");this.busy=!0;this.fx.animate({modes:["linear","node-property:alpha"],onComplete:function(){h.busy=!1;h.onClick(a,{onComplete:function(){c&&c.onComplete()}})}})}if(!this.busy){this.busy=!0;var h=this,j=this.canvas,k=this.graph.getNode(this.root),
m=this.graph.getNode(a);delete k.data.$orns;b=="animate"?(g.call(this),h.selectPath(m)):b=="replot"&&(g.call(this),this.select(this.root))}},addSubtree:function(a,b,c){b=="replot"?this.op.sum(a,h.extend({type:"replot"},c||{})):b=="animate"&&this.op.sum(a,h.extend({type:"fade:seq"},c||{}))},removeSubtree:function(a,b,c,g){var i=[];this.graph.getNode(a).eachLevel(+!b,!1,function(a){i.push(a.id)});c=="replot"?this.op.removeNode(i,h.extend({type:"replot"},g||{})):c=="animate"&&this.op.removeNode(i,h.extend({type:"fade:seq"},
g||{}))},select:function(b,e){var f=this.group,g=this.geom,i=this.graph.getNode(b),j=this.canvas;this.graph.getNode(this.root);var k=h.merge(this.controller,e),m=this;k.onBeforeCompute(i);this.selectPath(i);this.clickedNode=i;this.requestNodes(i,{onComplete:function(){f.hide(f.prepare(a.call(m)),k);g.setRightLevelToShow(i,j);m.compute("current");m.graph.eachNode(function(a){var b=a.pos.getc(!0);a.startPos.setc(b.x,b.y);a.endPos.setc(b.x,b.y);a.visited=!1});m.geom.translate(i.endPos.add({x:k.offsetX,
y:k.offsetY}).$scale(-1),["start","current","end"]);f.show(c.call(m));m.plot();k.onAfterCompute(m.clickedNode);k.onComplete()}})},onClick:function(a,b){var c=this.canvas,g=this,i=this.geom,j=this.config,k=h.merge(this.controller,{Move:{enable:!0,offsetX:j.offsetX||0,offsetY:j.offsetY||0},setRightLevelToShowConfig:!1,onBeforeRequest:h.empty,onBeforeContract:h.empty,onBeforeMove:h.empty,onBeforeExpand:h.empty},b);if(!this.busy){this.busy=!0;var m=this.graph.getNode(a);this.selectPath(m,this.clickedNode);
this.clickedNode=m;k.onBeforeCompute(m);k.onBeforeRequest(m);this.requestNodes(m,{onComplete:function(){k.onBeforeContract(m);g.contract({onComplete:function(){i.setRightLevelToShow(m,c,k.setRightLevelToShowConfig);k.onBeforeMove(m);g.move(m,{Move:k.Move,onComplete:function(){k.onBeforeExpand(m);g.expand(m,{onComplete:function(){g.busy=!1;k.onAfterCompute(a);k.onComplete()}})}})}})}})}}})}();$jit.ST.$extend=!0;$jit.ST.Op=new l({Implements:o.Op});$jit.ST.Group=new l({initialize:function(a){this.viz=
a;this.canvas=a.canvas;this.config=a.config;this.animation=new J;this.nodes=null},requestNodes:function(a,c){var b=0,d=a.length,e=this.viz;if(d==0)c.onComplete();for(var f=0;f<d;f++)c.request(a[f].id,a[f]._level,{onComplete:function(a,f){if(f&&f.children)f.id=a,e.op.sum(f,{type:"nothing"});++b==d&&(e.graph.computeLevels(e.root,0),c.onComplete())}})},contract:function(a,c){var b=this,a=this.prepare(a);this.animation.setOptions(h.merge(c,{$animating:!1,compute:function(a){a==1&&(a=0.99);b.plotStep(1-
a,c,this.$animating);this.$animating="contract"},complete:function(){b.hide(a,c)}})).start()},hide:function(a,c){for(var b=0;b<a.length;b++)a[b].eachLevel(1,!1,function(a){a.exist&&h.extend(a,{drawn:!1,exist:!1})});c.onComplete()},expand:function(a,c){var b=this;this.show(a);this.animation.setOptions(h.merge(c,{$animating:!1,compute:function(a){b.plotStep(a,c,this.$animating);this.$animating="expand"},complete:function(){b.plotStep(void 0,c,!1);c.onComplete()}})).start()},show:function(a){var c=this.config;
this.prepare(a);h.each(a,function(a){if(c.multitree&&!("$orn"in a.data)){delete a.data.$orns;var d=" ";a.eachSubnode(function(a){"$orn"in a.data&&d.indexOf(a.data.$orn)<0&&a.exist&&!a.drawn&&(d+=a.data.$orn+" ")});a.data.$orns=d}a.eachLevel(0,c.levelsToShow,function(a){if(a.exist)a.drawn=!0})})},prepare:function(a){return this.nodes=this.getNodesWithChildren(a)},getNodesWithChildren:function(a){var c=[],b=this.config;a.sort(function(a,b){return(a._depth<=b._depth)-(a._depth>=b._depth)});for(var d=
0;d<a.length;d++)if(a[d].anySubnode("exist")){for(var e=d+1,f=!1;!f&&e<a.length;e++)if(!b.multitree||"$orn"in a[e].data)f=f||a[d].isDescendantOf(a[e].id);f||c.push(a[d])}return c},plotStep:function(a,c,b){var d=this.viz,e=this.config,f=d.canvas.getCtx(),g=this.nodes,i,j,k={};for(i=0;i<g.length;i++){j=g[i];k[j.id]=[];var m=e.multitree&&!("$orn"in j.data),n=m&&j.data.$orns;j.eachSubgraph(function(a){if(m&&n&&n.indexOf(a.data.$orn)>0&&a.drawn)a.drawn=!1,k[j.id].push(a);else if((!m||!n)&&a.drawn)a.drawn=
!1,k[j.id].push(a)});j.drawn=!0}g.length>0&&d.fx.plot();for(i in k)h.each(k[i],function(a){a.drawn=!0});for(i=0;i<g.length;i++)j=g[i],f.save(),d.fx.plotSubtree(j,c,a,b),f.restore()},getSiblings:function(a){var c={};h.each(a,function(a){var d=a.getParents();if(d.length==0)c[a.id]=[a];else{var e=[];d[0].eachSubnode(function(a){e.push(a)});c[a.id]=e}});return c}});$jit.ST.Geom=new l({Implements:o.Geom,switchOrientation:function(a){this.config.orientation=a},dispatch:function(){var a=Array.prototype.slice.call(arguments),
c=a.shift(),b=a.length,d=function(a){return typeof a=="function"?a():a};if(b==2)return c=="top"||c=="bottom"?d(a[0]):d(a[1]);else if(b==4)switch(c){case "top":return d(a[0]);case "right":return d(a[1]);case "bottom":return d(a[2]);case "left":return d(a[3])}},getSize:function(a,c){var b=a.data,d=this.config,e=d.siblingOffset,b=d.multitree&&"$orn"in b&&b.$orn||d.orientation,d=a.getData("width")+e,e=a.getData("height")+e;return c?this.dispatch(b,d,e):this.dispatch(b,e,d)},getTreeBaseSize:function(a,
c,b){var d=this.getSize(a,!0),e=0,f=this;if(b(c,a))return d;if(c===0)return 0;a.eachSubnode(function(a){e+=f.getTreeBaseSize(a,c-1,b)});return(d>e?d:e)+this.config.subtreeOffset},getEdge:function(a,c,b){var d=function(b,c){return function(){return a.pos.add(new r(b,c))}},e=this.node,f=a.getData("width"),g=a.getData("height");if(c=="begin")if(e.align=="center")return this.dispatch(b,d(0,g/2),d(-f/2,0),d(0,-g/2),d(f/2,0));else if(e.align=="left")return this.dispatch(b,d(0,g),d(0,0),d(0,0),d(f,0));else if(e.align==
"right")return this.dispatch(b,d(0,0),d(-f,0),d(0,-g),d(0,0));else throw"align: not implemented";else if(c=="end")if(e.align=="center")return this.dispatch(b,d(0,-g/2),d(f/2,0),d(0,g/2),d(-f/2,0));else if(e.align=="left")return this.dispatch(b,d(0,0),d(f,0),d(0,g),d(0,0));else if(e.align=="right")return this.dispatch(b,d(0,-g),d(0,0),d(0,0),d(-f,0));else throw"align: not implemented";},getScaledTreePosition:function(a,c){var b=this.node,d=a.getData("width"),e=a.getData("height"),f=this.config.multitree&&
"$orn"in a.data&&a.data.$orn||this.config.orientation,g=function(b,d){return function(){return a.pos.add(new r(b,d)).$scale(1-c)}};if(b.align=="left")return this.dispatch(f,g(0,e),g(0,0),g(0,0),g(d,0));else if(b.align=="center")return this.dispatch(f,g(0,e/2),g(-d/2,0),g(0,-e/2),g(d/2,0));else if(b.align=="right")return this.dispatch(f,g(0,0),g(-d,0),g(0,-e),g(0,0));else throw"align: not implemented";},treeFitsInCanvas:function(a,c,b){c=c.getSize();c=this.dispatch(this.config.multitree&&"$orn"in a.data&&
a.data.$orn||this.config.orientation,c.width,c.height);return this.getTreeBaseSize(a,b,function(a,b){return a===0||!b.anySubnode()})<c}});$jit.ST.Plot=new l({Implements:o.Plot,plotSubtree:function(a,c,b,d){var e=this.viz,f=e.canvas,g=e.config,b=Math.min(Math.max(0.001,b),1);if(b>=0)a.drawn=!1,f=f.getCtx(),e=e.geom.getScaledTreePosition(a,b),f.translate(e.x,e.y),f.scale(b,b);this.plotTree(a,h.merge(c,{withLabels:!0,hideLabels:!!b,plotSubtree:function(){var b=g.multitree&&!("$orn"in a.data),c=b&&a.getData("orns");
return!b||c.indexOf(a.getData("orn"))>-1}}),d);if(b>=0)a.drawn=!0},getAlignedPos:function(a,c,b){var d=this.node;if(d.align=="center")a={x:a.x-c/2,y:a.y-b/2};else if(d.align=="left")d=this.config.orientation,a=d=="bottom"||d=="top"?{x:a.x-c/2,y:a.y}:{x:a.x,y:a.y-b/2};else if(d.align=="right")d=this.config.orientation,a=d=="bottom"||d=="top"?{x:a.x-c/2,y:a.y-b}:{x:a.x-c,y:a.y-b/2};else throw"align: not implemented";return a},getOrientation:function(a){var c=this.config,b=c.orientation;if(c.multitree)c=
a.nodeFrom,a=a.nodeTo,b="$orn"in c.data&&c.data.$orn||"$orn"in a.data&&a.data.$orn;return b}});$jit.ST.Label={};$jit.ST.Label.Native=new l({Implements:o.Label.Native,renderLabel:function(a,c){var b=a.getCtx(),d=c.pos.getc(!0),e=c.getData("width"),f=c.getData("height"),d=this.viz.fx.getAlignedPos(d,e,f);b.fillText(c.name,d.x+e/2,d.y+f/2)}});$jit.ST.Label.DOM=new l({Implements:o.Label.DOM,placeLabel:function(a,c,b){var d=c.pos.getc(!0),e=this.viz.config,f=e.Node,g=this.viz.canvas,h=c.getData("width"),
j=c.getData("height"),k=g.getSize(),m=d.x*g.scaleOffsetX+g.translateOffsetX,d=d.y*g.scaleOffsetY+g.translateOffsetY;if(f.align=="center")h={x:Math.round(m-h/2+k.width/2),y:Math.round(d-j/2+k.height/2)};else if(f.align=="left")e=e.orientation,h=e=="bottom"||e=="top"?{x:Math.round(m-h/2+k.width/2),y:Math.round(d+k.height/2)}:{x:Math.round(m+k.width/2),y:Math.round(d-j/2+k.height/2)};else if(f.align=="right")e=e.orientation,h=e=="bottom"||e=="top"?{x:Math.round(m-h/2+k.width/2),y:Math.round(d-j+k.height/
2)}:{x:Math.round(m-h+k.width/2),y:Math.round(d-j/2+k.height/2)};else throw"align: not implemented";j=a.style;j.left=h.x+"px";j.top=h.y+"px";j.display=this.fitsInCanvas(h,g)?"":"none";b.onPlaceLabel(a,c)}});$jit.ST.Label.SVG=new l({Implements:[$jit.ST.Label.DOM,o.Label.SVG],initialize:function(a){this.viz=a}});$jit.ST.Label.HTML=new l({Implements:[$jit.ST.Label.DOM,o.Label.HTML],initialize:function(a){this.viz=a}});$jit.ST.Plot.NodeTypes=new l({none:{render:h.empty,contains:h.lambda(!1)},circle:{render:function(a,
c){var b=a.getData("dim"),d=this.getAlignedPos(a.pos.getc(!0),b,b);b/=2;this.nodeHelper.circle.render("fill",{x:d.x+b,y:d.y+b},b,c)},contains:function(a,c){var b=a.getData("dim"),d=this.getAlignedPos(a.pos.getc(!0),b,b);b/=2;this.nodeHelper.circle.contains({x:d.x+b,y:d.y+b},c,b)}},square:{render:function(a,c){var b=a.getData("dim"),d=b/2,b=this.getAlignedPos(a.pos.getc(!0),b,b);this.nodeHelper.square.render("fill",{x:b.x+d,y:b.y+d},d,c)},contains:function(a,c){var b=a.getData("dim"),d=this.getAlignedPos(a.pos.getc(!0),
b,b);b/=2;this.nodeHelper.square.contains({x:d.x+b,y:d.y+b},c,b)}},ellipse:{render:function(a,c){var b=a.getData("width"),d=a.getData("height"),e=this.getAlignedPos(a.pos.getc(!0),b,d);this.nodeHelper.ellipse.render("fill",{x:e.x+b/2,y:e.y+d/2},b,d,c)},contains:function(a,c){var b=a.getData("width"),d=a.getData("height"),e=this.getAlignedPos(a.pos.getc(!0),b,d);this.nodeHelper.ellipse.contains({x:e.x+b/2,y:e.y+d/2},c,b,d)}},rectangle:{render:function(a,c){var b=a.getData("width"),d=a.getData("height"),
e=this.getAlignedPos(a.pos.getc(!0),b,d);this.nodeHelper.rectangle.render("fill",{x:e.x+b/2,y:e.y+d/2},b,d,c)},contains:function(a,c){var b=a.getData("width"),d=a.getData("height"),e=this.getAlignedPos(a.pos.getc(!0),b,d);this.nodeHelper.rectangle.contains({x:e.x+b/2,y:e.y+d/2},c,b,d)}}});$jit.ST.Plot.EdgeTypes=new l({none:h.empty,line:{render:function(a,c){var b=this.getOrientation(a),d=a.nodeFrom,e=a.nodeTo,f=d._depth<e._depth,g=this.viz.geom.getEdge(f?d:e,"begin",b),b=this.viz.geom.getEdge(f?e:
d,"end",b);this.edgeHelper.line.render(g,b,c)},contains:function(a,c){var b=this.getOrientation(a),d=a.nodeFrom,e=a.nodeTo,f=d._depth<e._depth,g=this.viz.geom.getEdge(f?d:e,"begin",b),b=this.viz.geom.getEdge(f?e:d,"end",b);return this.edgeHelper.line.contains(g,b,c,this.edge.epsilon)}},arrow:{render:function(a,c){var b=this.getOrientation(a),d=a.nodeFrom,e=a.nodeTo,f=a.getData("dim"),g=this.viz.geom.getEdge(d,"begin",b),b=this.viz.geom.getEdge(e,"end",b),e=a.data.$direction;this.edgeHelper.arrow.render(g,
b,f,e&&e.length>1&&e[0]!=d.id,c)},contains:function(a,c){var b=this.getOrientation(a),d=a.nodeFrom,e=a.nodeTo,f=d._depth<e._depth,g=this.viz.geom.getEdge(f?d:e,"begin",b),b=this.viz.geom.getEdge(f?e:d,"end",b);return this.edgeHelper.arrow.contains(g,b,c,this.edge.epsilon)}},"quadratic:begin":{render:function(a,c){var b=this.getOrientation(a),d=a.nodeFrom,e=a.nodeTo,f=d._depth<e._depth,g=this.viz.geom.getEdge(f?d:e,"begin",b),d=this.viz.geom.getEdge(f?e:d,"end",b),e=a.getData("dim"),f=c.getCtx();f.beginPath();
f.moveTo(g.x,g.y);switch(b){case "left":f.quadraticCurveTo(g.x+e,g.y,d.x,d.y);break;case "right":f.quadraticCurveTo(g.x-e,g.y,d.x,d.y);break;case "top":f.quadraticCurveTo(g.x,g.y+e,d.x,d.y);break;case "bottom":f.quadraticCurveTo(g.x,g.y-e,d.x,d.y)}f.stroke()}},"quadratic:end":{render:function(a,c){var b=this.getOrientation(a),d=a.nodeFrom,e=a.nodeTo,f=d._depth<e._depth,g=this.viz.geom.getEdge(f?d:e,"begin",b),d=this.viz.geom.getEdge(f?e:d,"end",b),e=a.getData("dim"),f=c.getCtx();f.beginPath();f.moveTo(g.x,
g.y);switch(b){case "left":f.quadraticCurveTo(d.x-e,d.y,d.x,d.y);break;case "right":f.quadraticCurveTo(d.x+e,d.y,d.x,d.y);break;case "top":f.quadraticCurveTo(d.x,d.y-e,d.x,d.y);break;case "bottom":f.quadraticCurveTo(d.x,d.y+e,d.x,d.y)}f.stroke()}},bezier:{render:function(a,c){var b=this.getOrientation(a),d=a.nodeFrom,e=a.nodeTo,f=d._depth<e._depth,g=this.viz.geom.getEdge(f?d:e,"begin",b),d=this.viz.geom.getEdge(f?e:d,"end",b),e=a.getData("dim"),f=c.getCtx();f.beginPath();f.moveTo(g.x,g.y);switch(b){case "left":f.bezierCurveTo(g.x+
e,g.y,d.x-e,d.y,d.x,d.y);break;case "right":f.bezierCurveTo(g.x-e,g.y,d.x+e,d.y,d.x,d.y);break;case "top":f.bezierCurveTo(g.x,g.y+e,d.x,d.y-e,d.x,d.y);break;case "bottom":f.bezierCurveTo(g.x,g.y-e,d.x,d.y+e,d.x,d.y)}f.stroke()}}});$jit.ST.Plot.NodeTypes.implement({"barchart-stacked":{render:function(a,c){var b=a.pos.getc(!0),d=a.getData("width"),e=a.getData("height"),f=this.getAlignedPos(b,d,e),b=f.x,f=f.y,g=a.getData("dimArray"),i=a.getData("valueArray"),j=a.getData("colorArray"),k=j.length,m=a.getData("stringArray"),
n=c.getCtx(),p={},l=a.getData("border"),o=a.getData("gradient"),q=a.getData("config"),r=q.orientation=="horizontal",v=q.showAggregates,B=q.showLabels,w=q.Label;if(j&&g&&m){for(var u=0,L=g.length,t=0,s=0;u<L;u++){n.fillStyle=n.strokeStyle=j[u%k];if(o){var A;A=r?n.createLinearGradient(b+t+g[u]/2,f,b+t+g[u]/2,f+e):n.createLinearGradient(b,f-t-g[u]/2,b+d,f-t-g[u]/2);var x=h.rgbToHex(h.map(h.hexToRgb(j[u%k].slice(1)),function(a){return a*0.5>>0}));A.addColorStop(0,x);A.addColorStop(0.5,j[u%k]);A.addColorStop(1,
x);n.fillStyle=A}r?n.fillRect(b+t,f,g[u],e):n.fillRect(b,f-t-g[u],d,g[u]);if(l&&l.name==m[u])p.acum=t,p.dimValue=g[u];t+=g[u]||0;s+=i[u]||0}if(l)n.save(),n.lineWidth=2,n.strokeStyle=l.color,r?n.strokeRect(b+p.acum+1,f+1,p.dimValue-2,e-2):n.strokeRect(b+1,f-p.acum-p.dimValue+1,d-2,p.dimValue-2),n.restore();if(w.type=="Native"){n.save();n.fillStyle=n.strokeStyle=w.color;n.font=w.style+" "+w.size+"px "+w.family;n.textBaseline="middle";g=v(a.name,s,a);if(g!==!1)g=g!==!0?g:s,r?(n.textAlign="right",n.fillText(g,
b+t-q.labelOffset,f+e/2)):(n.textAlign="center",n.fillText(g,b+d/2,f-e-w.size/2-q.labelOffset));if(B(a.name,s,a))r?(n.textAlign="center",n.translate(b-q.labelOffset-w.size/2,f+e/2),n.rotate(Math.PI/2),n.fillText(a.name,0,0)):(n.textAlign="center",n.fillText(a.name,b+d/2,f+w.size/2+q.labelOffset));n.restore()}}},contains:function(a,c){var b=a.pos.getc(!0),d=a.getData("width"),e=a.getData("height"),b=this.getAlignedPos(b,d,e),f=b.x,g=b.y,b=a.getData("dimArray"),h=a.getData("config").orientation=="horizontal";
if(h){if(c.x<f||c.x>f+d||c.y>g+e||c.y<g)return!1}else if(c.x<f||c.x>f+d||c.y>g||c.y<g-e)return!1;d=0;e=b.length;for(f=h?f:g;d<e;d++)if(g=b[d],h){if(f+=g,g=f,c.x<=g)return{name:a.getData("stringArray")[d],color:a.getData("colorArray")[d],value:a.getData("valueArray")[d],label:a.name}}else if(f-=g,g=f,c.y>=g)return{name:a.getData("stringArray")[d],color:a.getData("colorArray")[d],value:a.getData("valueArray")[d],label:a.name};return!1}},"barchart-grouped":{render:function(a,c){var b=a.pos.getc(!0),
d=a.getData("width"),e=a.getData("height"),f=this.getAlignedPos(b,d,e),b=f.x,f=f.y,g=a.getData("dimArray"),i=a.getData("valueArray"),j=i.length,k=a.getData("colorArray"),m=k.length,n=a.getData("stringArray"),p=c.getCtx(),l={},o=a.getData("border"),q=a.getData("gradient"),r=a.getData("config"),v=r.orientation=="horizontal",B=r.showAggregates,w=r.showLabels,u=r.Label,s=(v?e:d)/j;if(k&&g&&n){for(var t=0,x=0,A=0;t<j;t++){p.fillStyle=p.strokeStyle=k[t%m];if(q){var y;y=v?p.createLinearGradient(b+g[t]/2,
f+s*t,b+g[t]/2,f+s*(t+1)):p.createLinearGradient(b+s*t,f-g[t]/2,b+s*(t+1),f-g[t]/2);var C=h.rgbToHex(h.map(h.hexToRgb(k[t%m].slice(1)),function(a){return a*0.5>>0}));y.addColorStop(0,C);y.addColorStop(0.5,k[t%m]);y.addColorStop(1,C);p.fillStyle=y}v?p.fillRect(b,f+s*t,g[t],s):p.fillRect(b+s*t,f-g[t],s,g[t]);if(o&&o.name==n[t])l.acum=s*t,l.dimValue=g[t];x+=g[t]||0;A+=i[t]||0}if(o)p.save(),p.lineWidth=2,p.strokeStyle=o.color,v?p.strokeRect(b+1,f+l.acum+1,l.dimValue-2,s-2):p.strokeRect(b+l.acum+1,f-l.dimValue+
1,s-2,l.dimValue-2),p.restore();if(u.type=="Native"){p.save();p.fillStyle=p.strokeStyle=u.color;p.font=u.style+" "+u.size+"px "+u.family;p.textBaseline="middle";i=B(a.name,A,a);if(i!==!1)i=i!==!0?i:A,v?(p.textAlign="right",p.fillText(i,b+Math.max.apply(null,g)-r.labelOffset,f+e/2)):(p.textAlign="center",p.fillText(i,b+d/2,f-Math.max.apply(null,g)-u.size/2-r.labelOffset));if(w(a.name,A,a))v?(p.textAlign="center",p.translate(b-r.labelOffset-u.size/2,f+e/2),p.rotate(Math.PI/2),p.fillText(a.name,0,0)):
(p.textAlign="center",p.fillText(a.name,b+d/2,f+u.size/2+r.labelOffset));p.restore()}}},contains:function(a,c){var b=a.pos.getc(!0),d=a.getData("width"),e=a.getData("height"),f=this.getAlignedPos(b,d,e),b=f.x,f=f.y,g=a.getData("dimArray"),h=g.length,j=a.getData("config").orientation=="horizontal",h=(j?e:d)/h;if(j){if(c.x<b||c.x>b+d||c.y>f+e||c.y<f)return!1}else if(c.x<b||c.x>b+d||c.y>f||c.y<f-e)return!1;d=0;for(e=g.length;d<e;d++){var k=g[d];if(j){var m=f+h*d;if(c.x<=b+k&&c.y>=m&&c.y<=m+h)return{name:a.getData("stringArray")[d],
color:a.getData("colorArray")[d],value:a.getData("valueArray")[d],label:a.name}}else if(m=b+h*d,c.x>=m&&c.x<=m+h&&c.y>=f-k)return{name:a.getData("stringArray")[d],color:a.getData("colorArray")[d],value:a.getData("valueArray")[d],label:a.name}}return!1}}});$jit.BarChart=new l({st:null,colors:["#416D9C","#70A35E","#EBB056","#C74243","#83548B","#909291","#557EAA"],selected:{},busy:!1,initialize:function(a){this.controller=this.config=h.merge(v("Canvas","Margin","Label","BarChart"),{Label:{type:"Native"}},
a);var a=this.config.showLabels,c=h.type(a),b=this.config.showAggregates,d=h.type(b);this.config.showLabels=c=="function"?a:h.lambda(a);this.config.showAggregates=d=="function"?b:h.lambda(b);this.initializeViz()},initializeViz:function(){var a=this.config,c=this,b=a.type.split(":")[0],d=a.orientation=="horizontal",e={},b=new $jit.ST({injectInto:a.injectInto,width:a.width,height:a.height,orientation:d?"left":"bottom",levelDistance:0,siblingOffset:a.barsOffset,subtreeOffset:0,withLabels:a.Label.type!=
"Native",useCanvas:a.useCanvas,Label:{type:a.Label.type},Node:{overridable:!0,type:"barchart-"+b,align:"left",width:1,height:1},Edge:{type:"none"},Tips:{enable:a.Tips.enable,type:"Native",force:!0,onShow:function(b,c,d){a.Tips.onShow(b,d,c)}},Events:{enable:!0,type:"Native",onClick:function(b,c,d){a.Events.enable&&(b=c.getContains(),a.Events.onClick(b,c,d))},onMouseMove:function(b,d){if(a.hoveredColor)if(b){var e=d.getContains();c.select(b.id,e.name,e.index)}else c.select(!1,!1,!1)}},onCreateLabel:function(b,
c){var d=a.Label,f=c.getData("valueArray"),f=h.reduce(f,function(a,b){return a+b},0),g={wrapper:document.createElement("div"),aggregate:document.createElement("div"),label:document.createElement("div")},p=g.wrapper,l=g.label,o=g.aggregate,q=p.style,r=l.style,s=o.style;e[c.id]=g;p.appendChild(l);p.appendChild(o);if(!a.showLabels(c.name,f,c))r.display="none";if(!a.showAggregates(c.name,f,c))s.display="none";q.position="relative";q.overflow="visible";q.fontSize=d.size+"px";q.fontFamily=d.family;q.color=
d.color;q.textAlign="center";s.position=r.position="absolute";b.style.width=c.getData("width")+"px";b.style.height=c.getData("height")+"px";s.left=r.left="0px";l.innerHTML=c.name;b.appendChild(p)},onPlaceLabel:function(b,c){if(e[c.id]){var d=e[c.id],f=d.wrapper.style,g=d.label.style,h=d.aggregate.style,l=a.type.split(":")[0]=="grouped",o=a.orientation=="horizontal",q=c.getData("dimArray"),r=c.getData("valueArray"),s=l&&o?Math.max.apply(null,q):c.getData("width"),l=l&&!o?Math.max.apply(null,q):c.getData("height"),
o=parseInt(f.fontSize,10);if(q&&r){f.width=h.width=g.width=b.style.width=s+"px";for(var v=0,w=r.length,s=0;v<w;v++)q[v]>0&&(s+=r[v]);g.display=a.showLabels(c.name,s,c)?"":"none";q=a.showAggregates(c.name,s,c);h.display=q!==!1?"":"none";a.orientation=="horizontal"?(h.textAlign="right",g.textAlign="left",g.textIndex=h.textIndent=a.labelOffset+"px",h.top=g.top=(l-o)/2+"px"):(h.top=-o-a.labelOffset+"px",g.top=a.labelOffset+l+"px",b.style.top=parseInt(b.style.top,10)-l+"px");b.style.height=f.height=l+
"px";d.aggregate.innerHTML=q!==!0?q:s}}}}),f=b.canvas.getSize(),g=a.Margin;d?(b.config.offsetX=f.width/2-g.left-(a.showLabels&&a.labelOffset+a.Label.size),b.config.offsetY=(g.bottom-g.top)/2):(b.config.offsetY=-f.height/2+g.bottom+(a.showLabels&&a.labelOffset+a.Label.size),b.config.offsetX=(g.right-g.left)/2);this.delegate=b;this.canvas=this.delegate.canvas},loadJSON:function(a){if(!this.busy){this.busy=!0;for(var c=h.time(),b=[],d=this.delegate,e=h.splat(a.label),f=h.splat(a.color||this.colors),
g=this.config,i=!!g.type.split(":")[1],j=g.animate,k=g.orientation=="horizontal",m=this,n=0,a=a.values,p=a.length;n<p;n++){var l=a[n],o=h.splat(a[n].values);b.push({id:c+l.label,name:l.label,data:{value:o,$valueArray:o,$colorArray:f,$stringArray:e,$gradient:i,$config:g},children:[]})}d.loadJSON({id:c+"$root",name:"",data:{$type:"none",$width:1,$height:1},children:b});this.normalizeDims();d.compute();d.select(d.root);j?k?d.fx.animate({modes:["node-property:width:dimArray"],duration:1500,onComplete:function(){m.busy=
!1}}):d.fx.animate({modes:["node-property:height:dimArray"],duration:1500,onComplete:function(){m.busy=!1}}):this.busy=!1}},updateJSON:function(a,c){if(!this.busy){this.busy=!0;this.select(!1,!1,!1);var b=this.delegate,d=b.graph,e=this.config.animate,f=this,g=this.config.orientation=="horizontal";h.each(a.values,function(b){var c=d.getByName(b.label);c&&(c.setData("valueArray",h.splat(b.values)),a.label&&c.setData("stringArray",h.splat(a.label)))});this.normalizeDims();b.compute();b.select(b.root);
e&&(g?b.fx.animate({modes:["node-property:width:dimArray"],duration:1500,onComplete:function(){f.busy=!1;c&&c.onComplete()}}):b.fx.animate({modes:["node-property:height:dimArray"],duration:1500,onComplete:function(){f.busy=!1;c&&c.onComplete()}}))}},select:function(a,c){if(this.config.hoveredColor){var b=this.selected;if(b.id!=a||b.name!=c)b.id=a,b.name=c,b.color=this.config.hoveredColor,this.delegate.graph.eachNode(function(c){a==c.id?c.setData("border",b):c.setData("border",!1)}),this.delegate.plot()}},
getLegend:function(){var a={},c;this.delegate.graph.getNode(this.delegate.root).eachAdjacency(function(a){c=a.nodeTo});var b=c.getData("colorArray"),d=b.length;h.each(c.getData("stringArray"),function(c,f){a[c]=b[f%d]});return a},getMaxValue:function(){var a=0,c=this.config.type.split(":")[0]=="stacked";this.delegate.graph.eachNode(function(b){var b=b.getData("valueArray"),d=0;b&&(c?h.each(b,function(a){d+=+a}):d=Math.max.apply(null,b),a=a>d?a:d)});return a},setBarType:function(a){this.config.type=
a;this.delegate.config.Node.type="barchart-"+a.split(":")[0]},normalizeDims:function(){var a=0;this.delegate.graph.getNode(this.delegate.root).eachAdjacency(function(){a++});var c=this.getMaxValue()||1,b=this.delegate.canvas.getSize(),d=this.config,e=d.Margin,f=e.left+e.right,e=e.top+e.bottom,g=d.orientation=="horizontal",i=(b[g?"height":"width"]-(g?e:f)-(a-1)*d.barsOffset)/a,j=d.animate,k=b[g?"width":"height"]-(g?f:e)-(!g&&d.showAggregates&&d.Label.size+d.labelOffset)-(d.showLabels&&d.Label.size+
d.labelOffset),m=g?"height":"width",n=g?"width":"height";this.delegate.graph.eachNode(function(a){var b=0,d=[];h.each(a.getData("valueArray"),function(a){b+=+a;d.push(0)});a.setData(m,i);j?(a.setData(n,b*k/c,"end"),a.setData("dimArray",h.map(a.getData("valueArray"),function(a){return a*k/c}),"end"),a.getData("dimArray")||a.setData("dimArray",d)):(a.setData(n,b*k/c),a.setData("dimArray",h.map(a.getData("valueArray"),function(a){return a*k/c})))})}});I.ForceDirected=new l({getOptions:function(){var a=
this.canvas.getSize(),c=a.width,a=a.height,b=0;this.graph.eachNode(function(){b++});var d=c*a/b,e=Math.sqrt(d),f=this.config.levelDistance;return{width:c,height:a,tstart:c*0.1,nodef:function(a){return d/(a||1)},edgef:function(a){return e*(a-f)}}},compute:function(a,c){var b=h.splat(a||["current","start","end"]),d=this.getOptions();O.compute(this.graph,b,this.config);this.graph.computeLevels(this.root,0,"ignore");this.graph.eachNode(function(a){h.each(b,function(c){c=a.getPos(c);if(c.equals(r.KER))c.x=
d.width/5*(Math.random()-0.5),c.y=d.height/5*(Math.random()-0.5);a.disp={};h.each(b,function(b){a.disp[b]=G(0,0)})})});this.computePositions(b,d,c)},computePositions:function(a,c,b){var d=this.config.iterations,e=0,f=this;if(b)(function i(){for(var h=b.iter,k=0;k<h;k++)if(c.t=c.tstart,d&&(c.t*=1-e++/(d-1)),f.computePositionStep(a,c),d&&e>=d){b.onComplete();return}b.onStep(Math.round(e/(d-1)*100));setTimeout(i,1)})();else for(;e<d;e++)c.t=c.tstart*(1-e/(d-1)),this.computePositionStep(a,c)},computePositionStep:function(a,
c){var b=this.graph,d=Math.min,e=Math.max,f=G(0,0);b.eachNode(function(d){h.each(a,function(a){d.disp[a].x=0;d.disp[a].y=0});b.eachNode(function(b){b.id!=d.id&&h.each(a,function(a){var e=d.getPos(a),g=b.getPos(a);f.x=e.x-g.x;f.y=e.y-g.y;e=f.norm()||1;d.disp[a].$add(f.$scale(c.nodef(e)/e))})})});var g=!!b.getNode(this.root).visited;b.eachNode(function(b){b.eachAdjacency(function(d){var e=d.nodeTo;!!e.visited===g&&h.each(a,function(a){var d=b.getPos(a),g=e.getPos(a);f.x=d.x-g.x;f.y=d.y-g.y;d=f.norm()||
1;b.disp[a].$add(f.$scale(-c.edgef(d)/d));e.disp[a].$add(f.$scale(-1))})});b.visited=!g});var i=c.t,j=c.width/2,k=c.height/2;b.eachNode(function(b){h.each(a,function(a){var c=b.disp[a],f=c.norm()||1,a=b.getPos(a);a.$add(G(c.x*d(Math.abs(c.x),i)/f,c.y*d(Math.abs(c.y),i)/f));a.x=d(j,e(-j,a.x));a.y=d(k,e(-k,a.y))})})}});$jit.ForceDirected=new l({Implements:[N,y,I.ForceDirected],initialize:function(a){var c=$jit.ForceDirected,a=this.controller=this.config=h.merge(v("Canvas","Node","Edge","Fx","Tips",
"NodeStyles","Events","Navigation","Controller","Label"),{iterations:50,levelDistance:50},a);if(a.useCanvas)this.canvas=a.useCanvas,this.config.labelContainer=this.canvas.id+"-label";else{if(a.background)a.background=h.merge({type:"Circles"},a.background);this.canvas=new s(this,a);this.config.labelContainer=(typeof a.injectInto=="string"?a.injectInto:a.injectInto.id)+"-label"}this.graphOptions={klass:r,Node:{selected:!1,exist:!0,drawn:!0}};this.graph=new o(this.graphOptions,this.config.Node,this.config.Edge);
this.labels=new c.Label[a.Label.type](this);this.fx=new c.Plot(this,c);this.op=new c.Op(this);this.json=null;this.busy=!1;this.initializeExtras()},refresh:function(){this.compute();this.plot()},reposition:function(){this.compute("end")},computeIncremental:function(a){a=h.merge({iter:20,property:"end",onStep:h.empty,onComplete:h.empty},a||{});this.config.onBeforeCompute(this.graph.getNode(this.root));this.compute(a.property,a)},plot:function(){this.fx.plot()},animate:function(a){this.fx.animate(h.merge({modes:["linear"]},
a||{}))}});$jit.ForceDirected.$extend=!0;(function(a){a.Op=new l({Implements:o.Op});a.Plot=new l({Implements:o.Plot});a.Label={};a.Label.Native=new l({Implements:o.Label.Native});a.Label.SVG=new l({Implements:o.Label.SVG,initialize:function(a){this.viz=a},placeLabel:function(a,b,d){var e=b.pos.getc(!0),f=this.viz.canvas,g=f.translateOffsetX,h=f.translateOffsetY,j=f.scaleOffsetX,k=f.scaleOffsetY,f=f.getSize(),e={x:Math.round(e.x*j+g+f.width/2),y:Math.round(e.y*k+h+f.height/2)};a.setAttribute("x",e.x);
a.setAttribute("y",e.y);d.onPlaceLabel(a,b)}});a.Label.HTML=new l({Implements:o.Label.HTML,initialize:function(a){this.viz=a},placeLabel:function(a,b,d){var e=b.pos.getc(!0),f=this.viz.canvas,g=f.translateOffsetX,h=f.translateOffsetY,j=f.scaleOffsetX,k=f.scaleOffsetY,l=f.getSize(),e={x:Math.round(e.x*j+g+l.width/2),y:Math.round(e.y*k+h+l.height/2)},g=a.style;g.left=e.x+"px";g.top=e.y+"px";g.display=this.fitsInCanvas(e,f)?"":"none";d.onPlaceLabel(a,b)}});a.Plot.NodeTypes=new l({none:{render:h.empty,
contains:h.lambda(!1)},circle:{render:function(a,b){var d=a.pos.getc(!0),e=a.getData("dim");this.nodeHelper.circle.render("fill",d,e,b)},contains:function(a,b){var d=a.pos.getc(!0),e=a.getData("dim");return this.nodeHelper.circle.contains(d,b,e)}},ellipse:{render:function(a,b){var d=a.pos.getc(!0),e=a.getData("width"),f=a.getData("height");this.nodeHelper.ellipse.render("fill",d,e,f,b)},contains:function(a,b){var d=a.pos.getc(!0),e=a.getData("width"),f=a.getData("height");return this.nodeHelper.ellipse.contains(d,
b,e,f)}},square:{render:function(a,b){var d=a.pos.getc(!0),e=a.getData("dim");this.nodeHelper.square.render("fill",d,e,b)},contains:function(a,b){var d=a.pos.getc(!0),e=a.getData("dim");return this.nodeHelper.square.contains(d,b,e)}},rectangle:{render:function(a,b){var d=a.pos.getc(!0),e=a.getData("width"),f=a.getData("height");this.nodeHelper.rectangle.render("fill",d,e,f,b)},contains:function(a,b){var d=a.pos.getc(!0),e=a.getData("width"),f=a.getData("height");return this.nodeHelper.rectangle.contains(d,
b,e,f)}},triangle:{render:function(a,b){var d=a.pos.getc(!0),e=a.getData("dim");this.nodeHelper.triangle.render("fill",d,e,b)},contains:function(a,b){var d=a.pos.getc(!0),e=a.getData("dim");return this.nodeHelper.triangle.contains(d,b,e)}},star:{render:function(a,b){var d=a.pos.getc(!0),e=a.getData("dim");this.nodeHelper.star.render("fill",d,e,b)},contains:function(a,b){var d=a.pos.getc(!0),e=a.getData("dim");return this.nodeHelper.star.contains(d,b,e)}}});a.Plot.EdgeTypes=new l({none:h.empty,line:{render:function(a,
b){var d=a.nodeFrom.pos.getc(!0),e=a.nodeTo.pos.getc(!0);this.edgeHelper.line.render(d,e,b)},contains:function(a,b){var d=a.nodeFrom.pos.getc(!0),e=a.nodeTo.pos.getc(!0);return this.edgeHelper.line.contains(d,e,b,this.edge.epsilon)}},arrow:{render:function(a,b){var d=a.nodeFrom.pos.getc(!0),e=a.nodeTo.pos.getc(!0),f=a.getData("dim"),g=a.data.$direction;this.edgeHelper.arrow.render(d,e,f,g&&g.length>1&&g[0]!=a.nodeFrom.id,b)},contains:function(a,b){var d=a.nodeFrom.pos.getc(!0),e=a.nodeTo.pos.getc(!0);
return this.edgeHelper.arrow.contains(d,e,b,this.edge.epsilon)}}})})($jit.ForceDirected)})();