#ifndef CFENGINE_NOVA_DEPRECATED_H
#define CFENGINE_NOVA_DEPRECATED_H

// THE PURPOSE OF THIS HEADER FILE IS TO DECLARE FUNCTIONS THAT ARE PENDING REMOVAL,
// AND ARE ONLY USED IN NOVA. REMOVING ANY OF THESE BRINGS GOOD KARMA.

#include "cf.nova.h"

char *EscapeJson(char *s, char *out, int outSz);

#endif
