#!/bin/sh
#
# cfengine3
# 
#
# Created by Nakarin Phooripoom on 22/6/2011.
# Copyright 2010 Cfengine AS. All rights reserved.
#
### BEGIN INIT INFO
# Provides:          cfengine3
# Required-Start:    $local_fs $remote_fs $network $time
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: GNU configuration engine
# Description:       Tool for configuring and maintaining network machines
### END INIT INFO
#
# chkconfig: 2345 60 40
# description: Starts the cfengine daemons for remote and periodic \
#    execution of cfengine and for environment monitoring.
# set -e

##### start: Defined variables and conditios #####

CFEXECD=/var/cfengine/bin/cf-execd
CFSERVD=/var/cfengine/bin/cf-serverd
CFMOND=/var/cfengine/bin/cf-monitord
CFHUB=/var/cfengine/bin/cf-hub
MONGOD=/var/cfengine/bin/mongod

ECHO=/bin/echo
TOUCH=/bin/touch
RM=/bin/rm
KILL=/bin/kill
PKILL=/usr/bin/pkill

PATH=/sbin:/bin:/usr/sbin:/usr/bin:/var/cfengine/bin

# Has the package been 'removed' but not purged?
test -f $CFEXECD || exit 0

# default control file
DEFAULT=/etc/sysconfig/cfengine3
if [ -f $DEFAULT ]; then
	. $DEFAULT
else
	RUN_CF_EXECD=1
	RUN_CF_SERVERD=1
	RUN_CF_MONITORD=1
	RUN_CF_HUB=0
fi

# defualt is no OS
SUSE=0
REDHAT=0
DEBIAN=0

# SuSE
if [ -f /usr/bin/zypper ]; then
	SUSE=1
else
	SUSE=0
fi

# RedHat5/CentOS/Fedora
if [ -f /usr/bin/yum ]; then
	REDHAT=1
else
	REDHAT=0
fi

# Debian/Ubuntu
if [ -f /usr/bin/apt-get ]; then
	DEBIAN=1
else
	DEBIAN=0
fi

# Source function library. (Redhat/Centos/Fedora)
if [ -f /usr/bin/yum ] && [ -f /etc/rc.d/init.d/functions ]; then
	. /etc/rc.d/init.d/functions
	FUNC=1
else
	set -e
	FUNC=0
fi

# Check /sbin/startproc for SUSE
if [ -x /sbin/startproc ] && [ -f /etc/rc.status ]; then
	. /etc/rc.status
	rc_reset
	PROC=1
else
	PROC=0
fi

# Check something for Debian/Ubuntu
if [ -x /sbin/start-stop-daemon ]; then
	SSD=1
else
	SSD=0
fi

# Grep PID
cfexecd_status=`ps waxu|grep -v grep|grep cf-execd|awk -F' ' '{print $2}'`
cfserverd_status=`ps waxu|grep -v grep|grep cf-serverd|awk -F' ' '{print $2}'`
cfmonitord_status=`ps waxu|grep -v grep|grep cf-monitord|awk -F' ' '{print $2}'`
cfhub_status=`ps waxu|grep -v grep|grep cf-hub|awk -F' ' '{print $2}'`
mongod_status=`ps waxu|grep -v grep|grep /var/cfengine/bin/mongod|awk -F' ' '{print $2}'`

##### end: Defined variables and conditions #####

### start scripting here ###

case "$1" in
	start)
		# start cf-execd
		# Redhat/Centos/Fedora
		if [ "$RUN_CF_EXECD" = "1" ] && [ "$REDHAT" = "1" ] && [ "$FUNC" = "1" ]; then
			$ECHO -n "Starting `basename $CFEXECD`: "
			daemon $CFEXECD
			$TOUCH /var/lock/subsys/`basename $CFEXECD`
			$ECHO
		elif [ "$RUN_CF_EXECD" = "1" ] && [ "$REDHAT" = "1" ] && [ "$FUNC" = "0" ]; then
			$ECHO -n "Starting `basename $CFEXECD`: "
			$CFEXECD
			$TOUCH /var/lock/subsys/`basename $CFEXECD`
			$ECHO
		fi
		# SUSE
		if [ "$RUN_CF_EXECD" = "1" ] && [ "$SUSE" = "1" ] && [ "$PROC" = "1" ]; then
			$ECHO -n "Starting `basename $CFEXECD`: "
			/sbin/startproc $CFEXECD
			rc_status -v
			$TOUCH /var/run/`basename $CFEXECD`.pid
		elif [ "$RUN_CF_EXECD" = "1" ] && [ "$SUSE" = "1" ] && [ "$PROC" = "0" ]; then
			$ECHO -n "Starting `basename $CFEXECD`: "
			$CFEXECD
			$TOUCH /var/run/`basename $CFEXECD`.pid
		fi
		# Debian/Ubuntu
		if [ "$RUN_CF_EXECD" = "1" ] && [ "$DEBIAN" = "1" ] && [ "$SSD" = "1" ]; then
			$ECHO -n "Starting `basename $CFEXECD`: "
			/sbin/start-stop-daemon --start --verbose --exec $CFEXECD
			$TOUCH /var/lock/`basename $CFEXECD`
		elif [ "$RUN_CF_EXECD" = "1" ] && [ "$DEBIAN" = "1" ] && [ "$SSD" = "0" ]; then
			$ECHO -n "Starting `basename $CFEXECD`: "
			$CFEXECD
			$TOUCH /var/lock/`basename $CFEXECD`
			$ECHO
		fi
		
		# start cf-serverd
		# Redhat/Centos/Fedora
		if [ "$RUN_CF_SERVERD" = "1" ] && [ "$REDHAT" = "1" ] && [ "$FUNC" = "1" ]; then
			$ECHO -n "Starting `basename $CFSERVD`: "
			daemon $CFSERVD
			$TOUCH /var/lock/subsys/`basename $CFSERVD`
			$ECHO
		elif [ "$RUN_CF_SERVERD" = "1" ] && [ "$REDHAT" = "1" ] && [ "$FUNC" = "0" ]; then
			$ECHO -n "Starting `basename $CFSERVD`: "
			$CFSERVD
			$TOUCH /var/lock/subsys/`basename $CFSERVD`
			$ECHO
		fi
		# SUSE
		if [ "$RUN_CF_SERVERD" = "1" ] && [ "$SUSE" = "1" ] && [ "$PROC" = "1" ]; then
			$ECHO -n "Starting `basename $CFSERVD`: "
			/sbin/startproc $CFSERVD
			rc_status -v
			$TOUCH /var/run/`basename $CFSERVD`.pid
		elif [ "$RUN_CF_SERVERD" = "1" ] && [ "$SUSE" = "1" ] && [ "$PROC" = "0" ]; then
			$ECHO -n "Starting `basename $CFSERVD`: "
			$CFSERVD
			$TOUCH /var/run/`basename $CFSERVD`.pid
		fi
		# Debian/Ubuntu
		if [ "$RUN_CF_SERVERD" = "1" ] && [ "$DEBIAN" = "1" ] && [ "$SSD" = "1" ]; then
			$ECHO -n "Starting `basename $CFSERVD`: "
			/sbin/start-stop-daemon --start --verbose --exec $CFSERVD
			$TOUCH /var/lock/`basename $CFSERVD`
		elif [ "$RUN_CF_SERVERD" = "1" ] && [ "$DEBIAN" = "1" ] && [ "$SSD" = "0" ]; then
			$ECHO -n "Starting `basename $CFSERVD`: "
			$CFSERVD
			$TOUCH /var/lock/`basename $CFSERVD`
			$ECHO
		fi
		
		# start cf-monitord
		# Redhat/Centos/Fedora
		if [ "$RUN_CF_MONITORD" = "1" ] && [ "$REDHAT" = "1" ] && [ "$FUNC" = "1" ]; then
			$ECHO -n "Starting `basename $CFMOND`: "
			daemon $CFMOND
			$TOUCH /var/lock/subsys/`basename $CFMOND`
			$ECHO
		elif [ "$RUN_CF_MONITORD" = "1" ] && [ "$REDHAT" = "1" ] && [ "$FUNC" = "0" ]; then
			$ECHO -n "Starting `basename $CFMOND`: "
			$CFMOND
			$TOUCH /var/lock/subsys/`basename $CFMOND`
			$ECHO
		fi
		# SUSE
		if [ "$RUN_CF_MONITORD" = "1" ] && [ "$SUSE" = "1" ] && [ "$PROC" = "1" ]; then
			$ECHO -n "Starting `basename $CFMOND`: "
			/sbin/startproc $CFMOND
			rc_status -v
			$TOUCH /var/run/`basename $CFMOND`.pid
		elif [ "$RUN_CF_MONITORD" = "1" ] && [ "$SUSE" = "1" ] && [ "$PROC" = "0" ]; then
			$ECHO -n "Starting `basename $CFMOND`: "
			$CFMOND
			$TOUCH /var/run/`basename $CFMOND`.pid
		fi
		# Debian/Ubuntu
		if [ "$RUN_CF_MONITORD" = "1" ] && [ "$DEBIAN" = "1" ] && [ "$SSD" = "1" ]; then
			$ECHO -n "Starting `basename $CFMOND`: "
			/sbin/start-stop-daemon --start --verbose --exec $CFMOND
			$TOUCH /var/lock/`basename $CFMOND`
		elif [ "$RUN_CF_MONTIROD" = "1" ] && [ "$DEBIAN" = "1" ] && [ "$SSD" = "0" ]; then
			$ECHO -n "Starting `basename $CFMOND`: "
			$CFMOND
			$TOUCH /var/lock/`basename $CFMOND`
			$ECHO
		fi
		
		# start cf-hub
		# Redhat/Centos/Fedora
		if [ "$RUN_CF_HUB" = "1" ] && [ "$REDHAT" = "1" ] && [ "$FUNC" = "1" ]; then
			$ECHO -n "Starting `basename $CFHUB`: "
			daemon $CFHUB
			$TOUCH /var/lock/subsys/`basename $CFHUB`
			$ECHO
		elif [ "$RUN_CF_HUB" = "1" ] && [ "$REDHAT" = "1" ] && [ "$FUNC" = "0" ]; then
			$ECHO -n "Starting `basename $CFHUB`: "
			$CFHUB
			$TOUCH /var/lock/subsys/`basename $CFHUB`
			$ECHO
		fi
		# SUSE
		if [ "$RUN_CF_HUB" = "1" ] && [ "$SUSE" = "1" ] && [ "$PROC" = "1" ]; then
			$ECHO -n "Starting `basename $CFHUB`: "
			/sbin/startproc $CFHUB
			rc_status -v
			$TOUCH /var/run/`basename $CFHUB`.pid
		elif [ "$RUN_CF_HUB" = "1" ] && [ "$SUSE" = "1" ] && [ "$PROC" = "0" ]; then
			$ECHO -n "Starting `basename $CFHUB`: "
			$CFHUB
			$TOUCH /var/run/`basename $CFHUB`.pid
		fi
		# Debian/Ubuntu
		if [ "$RUN_CF_HUB" = "1" ] && [ "$DEBIAN" = "1" ] && [ "$SSD" = "1" ]; then
			$ECHO -n "Starting `basename $CFHUB`: "
			/sbin/start-stop-daemon --start --verbose --exec $CFHUB
			$TOUCH /var/lock/`basename $CFHUB`
		elif [ "$RUN_CF_HUB" = "1" ] && [ "$DEBIAN" = "1" ] && [ "$SSD" = "0" ]; then
			$ECHO -n "Starting `basename $CFHUB`: "
			$CFHUB
			$TOUCH /var/lock/`basename $CFHUB`
			$ECHO
		fi
	;;
	stop)
		# shutdown cf-execd
		# Redhat/Centos/Fedora
		if [ "$RUN_CF_EXECD" = "1" ] && [ "$REDHAT" = "1" ] && [ "$FUNC" = "1" ]; then
			$ECHO -n "Shutting down `basename $CFEXECD`: "
			killproc $CFEXECD
			$RM -f /var/lock/subsys/`basename $CFEXECD`
			$ECHO
		elif [ "$RUN_CF_EXECD" = "1" ] && [ "$REDHAT" = "1" ] && [ "$FUNC" = "0" ]; then
			$ECHO -n "Shutting down `basename $CFEXECD`: "
			$PKILL `basename $CFEXECD`
			$RM -f /var/lock/subsys/`basename $CFEXECD`
			$ECHO
		fi
		# SUSE
		if [ "$RUN_CF_EXECD" = "1" ] && [ "$SUSE" = "1" ] && [ "$PROC" = "1" ]; then
			if [ $cfexecd_status ]; then
				$ECHO -n "Shutting down `basename $CFEXECD`: "
				/sbin/killproc -TERM $CFEXECD
				rc_status -v
				$RM /var/run/`basename $CFEXECD`.pid
			fi
		elif [ "$RUN_CF_EXECD" = "1" ] && [ "$SUSE" = "1" ] && [ "$PROC" = "0" ]; then
			if [ $cfexecd_status ]; then
				$ECHO -n "Shutting down `basename $CFEXECD`: "
				$PKILL `basename $CFEXECD`
				$RM /var/run/`basename $CFEXECD`.pid
			fi
		fi
		# Debian/Ubuntu
		if [ "$RUN_CF_EXECD" = "1" ] && [ "$DEBIAN" = "1" ] && [ "$SSD" = "1" ]; then
			if [ $cfexecd_status ]; then
				$ECHO -n "Shutting down `basename $CFEXECD` ... "
				/sbin/start-stop-daemon -o --stop --retry 5 --name `basename $CFEXECD`
				$RM /var/lock/`basename $CFEXECD`
				$ECHO
			fi
		elif [ "$RUN_CF_EXECD" = "1" ] && [ "$DEBIAN" = "1" ] && [ "$SSD" = "0" ]; then
			if [ $cfexecd_status ]; then
				$ECHO -n "Shutting down `basename $CFEXECD` ... "
				$PKILL `basename $CFEXECD`
				$RM /var/lock/`basename $CFEXECD`
				$ECHO
			fi
		fi
		
		# shutdown cf-serverd
		# Redhat/Centos/Fedora
		if [ "$RUN_CF_SERVERD" = "1" ] && [ "$REDHAT" = "1" ] && [ "$FUNC" = "1" ]; then
			$ECHO -n "Shutting down `basename $CFSERVD`: "
			killproc $CFSERVD
			$RM -f /var/lock/subsys/`basename $CFSERVD`
			$ECHO
		elif [ "$RUN_CF_SERVERD" = "1" ] && [ "$REDHAT" = "1" ] && [ "$FUNC" = "0" ]; then
			$ECHO -n "Shutting down `basename $CFSERVD`: "
			$PKILL `basename $CFSERVD`
			$RM -f /var/lock/subsys/`basename $CFSERVD`
			$ECHO
		fi
		# SUSE
		if [ "$RUN_CF_SERVERD" = "1" ] && [ "$SUSE" = "1" ] && [ "$PROC" = "1" ]; then
			if [ $cfserverd_status ]; then
				$ECHO -n "Shutting down `basename $CFSERVD`: "
				/sbin/killproc -TERM $CFSERVD
				rc_status -v
				$RM /var/run/`basename $CFSERVD`.pid
			fi
		elif [ "$RUN_CF_SERVERD" = "1" ] && [ "$SUSE" = "1" ] && [ "$PROC" = "0" ]; then
			if [ $cfserverd_status ]; then
				$ECHO -n "Shutting down `basename $CFSERVD`: "
				$PKILL `basename $CFSERVD`
				$RM /var/run/`basename $CFSERVD`.pid
			fi
		fi
		# Debian/Ubuntu
		if [ "$RUN_CF_SERVERD" = "1" ] && [ "$DEBIAN" = "1" ] && [ "$SSD" = "1" ]; then
			if [ $cfserverd_status ]; then
				$ECHO -n "Shutting down `basename $CFSERVD` ... "
				/sbin/start-stop-daemon -o --stop --retry 5 --name `basename $CFSERVD`
				$RM /var/lock/`basename $CFSERVD`
				$ECHO
			fi
		elif [ "$RUN_CF_SERVERD" = "1" ] && [ "$DEBIAN" = "1" ] && [ "$SSD" = "0" ]; then
			if [ $cfserverd_status ]; then
				$ECHO -n "Shutting down `basename $CFSERVD` ... "
				$PKILL `basename $CFSERVD`
				$RM /var/lock/`basename $CFSERVD`
				$ECHO
			fi
		fi
		
		# shutdown cf-monitord
		# Redhat/Centos/Fedora
		if [ "$RUN_CF_MONITORD" = "1" ] && [ "$REDHAT" = "1" ] && [ "$FUNC" = "1" ]; then
			$ECHO -n "Shutting down `basename $CFMOND`: "
			killproc $CFMOND
			$RM -f /var/lock/subsys/`basename $CFMOND`
			$ECHO
		elif [ "$RUN_CF_MONITORD" = "1" ] && [ "$REDHAT" = "1" ] && [ "$FUNC" = "0" ]; then
			$ECHO -n "Shutting down `basename $CFMOND`: "
			$PKILL `basename $CFMOND`
			$RM -f /var/lock/subsys/`basename $CFMOND`
			$ECHO
		fi
		# SUSE
		if [ "$RUN_CF_MONITORD" = "1" ] && [ "$SUSE" = "1" ] && [ "$PROC" = "1" ]; then
			if [ $cfmonitord_status ]; then
				$ECHO -n "Shutting down `basename $CFMOND`: "
				/sbin/killproc -TERM $CFMOND
				rc_status -v
				$RM /var/run/`basename $CFMOND`.pid
			fi
		elif [ "$RUN_CF_MONITORD" = "1" ] && [ "$SUSE" = "1" ] && [ "$PROC" = "0" ]; then
			if [ $cfmonitord_status ]; then
				$ECHO -n "Shutting down `basename $CFMOND`: "
				$PKILL `basename $CFMOND`
				$RM /var/run/`basename $CFMOND`.pid
			fi
		fi
		# Debian/Ubuntu
		if [ "$RUN_CF_MONITORD" = "1" ] && [ "$DEBIAN" = "1" ] && [ "$SSD" = "1" ]; then
			if [ $cfmonitord_status ]; then
				$ECHO -n "Shutting down `basename $CFMOND` ... "
				/sbin/start-stop-daemon -o --stop --retry 5 --name `basename $CFMOND`
				$RM /var/lock/`basename $CFMOND`
				$ECHO
			fi
		elif [ "$RUN_CF_MONITORD" = "1" ] && [ "$DEBIAN" = "1" ] && [ "$SSD" = "0" ]; then
			if [ $cfmonitord_status ]; then
				$ECHO -n "Shutting down `basename $CFMOND` ... "
				$PKILL `basename $CFMONITORD`
				$RM /var/lock/`basename $CFMOND`
				$ECHO
			fi
		fi
		
		# shutdown cf-hub
		# Redhat/Centos/Fedora
		if [ "$REDHAT" = "1" ] && [ "$FUNC" = "1" ]; then
			if [ $cfhub_status ]; then
				$ECHO -n "Shutting down `basename $CFHUB`: "
				killproc $CFHUB
				if [ -f /var/lock/subsys/`basename $CFHUB` ]; then
					$RM -f /var/lock/subsys/`basename $CFHUB`
				fi
				$ECHO
			fi
		elif [ "$REDHAT" = "1" ] && [ "$FUNC" = "0" ]; then
			if [ $cfhub_status ]; then
				$ECHO -n "Shutting down `basename $CFHUB`: "
				$PKILL `basename $CFHUB`
				if [ -f /var/lock/subsys/`basename $CFHUB` ]; then
					$RM -f /var/lock/subsys/`basename $CFHUB`
				fi
				$ECHO
			fi
		fi
		# SUSE
		if [ "$RUN_CF_HUB" = "1" ] && [ "$SUSE" = "1" ] && [ "$PROC" = "1" ]; then
			if [ $cfhub_status ]; then
				$ECHO -n "Shutting down `basename $CFHUB`: "
				/sbin/killproc -TERM $CFHUB
				rc_status -v
				if [ -f /var/run/`basename $CFHUB`.pid ]; then
					$RM /var/run/`basename $CFHUB`.pid
				fi
			fi
		elif [ "$RUN_CF_HUB" = "1" ] && [ "$SUSE" = "1" ] && [ "$PROC" = "0" ]; then
			if [ $cfhub_status ]; then
				$ECHO -n "Shutting down `basename $CFHUB`: "
				$PKILL `basename $CFHUB`
				if [ -f /var/run/`basename $CFHUB`.pid ]; then
					$RM /var/run/`basename $CFHUB`.pid
				fi
			fi
		fi
		# Debian/Ubuntu
		if [ "$DEBIAN" = "1" ] && [ "$SSD" = "1" ]; then
			if [ $cfhub_status ]; then
				$ECHO -n "Shutting down `basename $CFHUB` ... "
				/sbin/start-stop-daemon -o --stop --retry 5 --name `basename $CFHUB`
				if [ -f /var/lock/`basename $CFHUB` ]; then
					$RM /var/lock/`basename $CFHUB`
				fi
				$ECHO
			fi
		elif [ "$DEBIAN" = "1" ] && [ "$SSD" = "0" ]; then
			if [ $cfhub_status ]; then
				$ECHO -n "Shutting down `basename $CFHUB` ... "
				$PKILL `basename $CFHUB`
				if [ -f /var/lock/`basename $CFHUB` ]; then
					$RM /var/lock/`basename $CFHUB`
				fi
				$ECHO
			fi
		fi

		# shutdown mongod
		# Redhat/Centos/Fedora
		# SUSE
		# Debian/Ubuntu
		if [ $mongod_status ]; then
			$ECHO -n "Shutting down mongod ... "
			$KILL -15 $mongod_status
			if [ -f /var/cfengine/state/mongod.lock ]; then
				$RM /var/cfengine/state/mongod.lock
			fi
			$ECHO
		fi
	;;
	status)
		# status cf-execd
		# Redhat/Centos/Fedora
		if [ "$REDHAT" = "1" ] && [ "$FUNC" = "1" ]; then
			status $CFEXECD
		elif [ "$REDHAT" = "1" ] && [ "$FUNC" = "0" ]; then
			if [ $cfexecd_status ]; then
				$ECHO "cf-execd (pid $cfexecd_status) is running..."
			else 
				$ECHO "cf-execd is not running"
			fi
		fi
		# SUSE
		if [ "$RUN_CF_EXECD" = "1" ] && [ "$SUSE" = "1" ] && [ "$PROC" = "1" ]; then
			if [ $cfexecd_status ]; then
				$ECHO -n "Checking for `basename $CFEXECD` "
				checkproc $CFEXECD
				rc_status -v
			fi
		fi
		# Debain/Ubuntu
		if [ "$DEBIAN" = "1" ]; then
			if [ $cfexecd_status ]; then
				$ECHO "cf-execd (pid $cfexecd_status) is running..."
			else 
				$ECHO "cf-execd is not running"
			fi
		fi
		
		# status cf-serverd
		# Redhat/Centos/Fedora
		if [ "$REDHAT" = "1" ] && [ "$FUNC" = "1" ]; then
			status $CFSERVD
		elif [ "$REDHAT" = "1" ] && [ "$FUNC" = "0" ]; then
			if [ $cfserverd_status ]; then
				$ECHO "cf-serverd (pid $cfserverd_status) is running..."
			else
				$ECHO "cf-serverd is not running"
			fi
		fi
		# SUSE
		if [ "$RUN_CF_SERVERD" = "1" ] && [ "$SUSE" = "1" ] && [ "$PROC" = "1" ]; then
			if [ $cfserverd_status ]; then
				$ECHO -n "Checking for `basename $CFSERVD` "
				checkproc $CFSERVD
				rc_status -v
			fi
		fi
		# Debain/Ubuntu
		if [ "$DEBIAN" = "1" ]; then
			if [ $cfserverd_status ]; then
				$ECHO "cf-serverd (pid $cfserverd_status) is running..."
			else 
				$ECHO "cf-serverd is not running"
			fi
		fi
		
		# status cf-monitord
		# Redhat/Centos/Fedora
		if [ "$REDHAT" = "1" ] && [ "$FUNC" = "1" ]; then
			status $CFMOND
		elif [ "$REDHAT" = "1" ] && [ "$FUNC" = "0" ]; then
			if [ $cfmonitord_status ]; then
				$ECHO "cf-monitord (pid $cfmonitord_status) is running..."
			else
				$ECHO "cf-monitord is not running"
			fi
		fi
		# SUSE
		if [ "$RUN_CF_MONITORD" = "1" ] && [ "$SUSE" = "1" ] && [ "$PROC" = "1" ]; then
			if [ $cfmonitord_status ]; then
				echo -n "Checking for `basename $CFMOND` "
				checkproc $CFMOND
				rc_status -v
			fi
		fi
		# Debain/Ubuntu
		if [ "$DEBIAN" = "1" ]; then
			if [ $cfmonitord_status ]; then
				$ECHO "cf-monitord (pid $cfmonitord_status) is running..."
			else 
				$ECHO "cf-monitord is not running"
			fi
		fi
		
		# status cf-hub
		# Redhat/Centos/Fedora
		if [ "$REDHAT" = "1" ] && [ "$FUNC" = "1" ]; then
			status $CFHUB
		elif [ "$REDHAT" = "1" ] && [ "$FUNC" = "0" ]; then
			if [ $cfhub_status ]; then
				$ECHO "cf-hub (pid $cfhub_status) is running..."
			else
				$ECHO "cf-hub is not running"
			fi	
		fi
		# SUSE
		if [ $cfhub_status ] && [ "$SUSE" = "1" ] && [ "$PROC" = "1" ]; then
			echo -n "Checking for `basename $CFHUB` "
			checkproc $CFHUB
			rc_status -v
		fi
		# Debain/Ubuntu
		if [ $cfhub_status ] && [ "$DEBIAN" = "1" ]; then
			$ECHO "cf-hub (pid $cfhub_status) is running..."
		elif [ "$DEBIAN" = "1" ]; then
			$ECHO "cf-hub is not running"
		fi


		# status mongod
		# Redhat/Centos/Fedora
		if [ "$REDHAT" = "1" ] && [ "$FUNC" = "1" ]; then
			status mongod
		elif [ "$REDHAT" = "1" ] && [ "$FUNC" = "0" ]; then
			if [ $mongod_status ]; then
				$ECHO "mongod (pid $mongod_status) is running..."
			else
				$ECHO "mongod is not running"
			fi	
		fi
		# SUSE
		if [ "$SUSE" = "1" ] && [ "$PROC" = "1" ]; then
			if [ $mongod_status ]; then
				echo -n "Checking for mongod "
				checkproc $MONGOD
				rc_status -v
			fi
		fi
		# Debain/Ubuntu
		if [ "$DEBIAN" = "1" ]; then
			if [ $mongod_status ]; then
				$ECHO "mongod (pid $mongod_status) is running..."
			else 
				$ECHO "mongod is not running"
			fi
		fi
	;;
	restart|reload|force-reload)
		$ECHO "cf-execd has 1-minute process-sleeping lock time by default. It would take up to a minute to restart it."
		$0 stop
		sleep 60
		$0 start
	;;
	*)
		N=/etc/init.d/cfengine3
		echo "Usage: $N {start|stop|status|restart|reload|force-reload}" >&2
		exit 1
	;;
esac
